### ISSUE TITLE
Customizer.py doesn't replace double backslash with single forward slash on Windows, causing WinError 5

### ISSUE THREAD

**Issue by torchatlas** [dragonwocky/notion-enhancer#10]
**describe the bug**
[WinError 5] Access is denied: 'C:/Users/Torch/AppData/Local/Programs/Notion/resources/app\\node_modules\\cld\\build\\Release\\cld.node'

**expected behaviour**
Looking at customiser.py, I think it was supposed to replace the double backslash with a single forward slash when it detected Windows. However, it seems to have not done that.

**screenshots**
![image](https://user-images.githubusercontent.com/12666855/86127472-eefeb580-baad-11ea-927f-6be4fc381776.png)

**platform**
windows 10 v2004. Ran Python 3.8 with PowerShell.

**Comment by dragonwocky** [comment]
can you confirm whether babcae1bd5f5a19e9698eb87d50a038922081321 has fixed this?

**Comment by torchatlas** [comment]
I tried the latest commit, [`d3d3b4`](https://github.com/dragonwocky/notion-enhancer/commit/d3d3b4007f5ecd9298ee3b2ac18dc19f7fe6ba39), and I'm no longer getting this issue!
