### ISSUE TITLE
The extensions

### ISSUE THREAD

**Issue by vyannn** [dragonwocky/notion-enhancer#100]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
blue text is purple; most extensions don't work except focus mode

**expected behaviour**

**screenshots**
![Screenshot (47)](https://user-images.githubusercontent.com/71185017/92999181-9e95e080-f551-11ea-9707-021e8cc6d954.png)
![Screenshot (50)](https://user-images.githubusercontent.com/71185017/92999188-a81f4880-f551-11ea-96d4-99332235af17.png)

**platform**
windows 10

**Comment by dragonwocky** [comment]
@vyannn colour mixup and property layout not working are both known bugs / a fix will be released soon.... everything else should be working though? Please be specific about which extensions aren't working.

**Comment by vyannn** [comment]
Hello! The other extensions are working now. Color mixup and property layout are the only issues now, thank you!
