### ISSUE TITLE
White notion on start up

### ISSUE THREAD

**Issue by Guilherme5342** [dragonwocky/notion-enhancer#103]
**what is the bug? :** When the notion opens for the first time when I start the computer it stays like a white page, I have to restart the app for it to load properly

**screenshots**
![image](https://user-images.githubusercontent.com/53620734/93465294-f66d7800-f8c0-11ea-892d-9367a6e6fce7.png)
![image](https://user-images.githubusercontent.com/53620734/93465329-02f1d080-f8c1-11ea-9beb-d0413f36e97b.png)

I recorded my screen but github doesn't let me upload it, can I send it via Discord? (Or if you have other ideia)

**platform**: Windows 10, desktop app

**Comment by dragonwocky** [comment]
sure, message me on discord. do you have any extensions enabled? what platform are you on? does anything show in the console? (if you're on windows/linux, open with `ctrl+shift+L`)

**Comment by Guilherme5342** [comment]
Windows 10, desktop app, I will restart the pc so I can see the console. The extensions I'm using: property-layout, weekly view, emoji sets (joypixels)

**Comment by Guilherme5342** [comment]
![image](https://user-images.githubusercontent.com/53620734/93475221-c2994f00-f8ce-11ea-83d9-74f0038cb4f2.png)
![image](https://user-images.githubusercontent.com/53620734/93475246-c88f3000-f8ce-11ea-873e-89bb087f80e1.png)
![image](https://user-images.githubusercontent.com/53620734/93475339-dd6bc380-f8ce-11ea-8820-025e59258239.png)

**Comment by dragonwocky** [comment]
@Guilherme5342 this looks like something's gone wrong on your end. Only things I can think of to do are to remove/reapply the enhancer and/or reinstall Notion... if it still happens after that let me know.

**Comment by Guilherme5342** [comment]
ok, I will try reinstalling notion, only with time I'll know if worked. Thanks

**Comment by dragonwocky** [comment]
does this still occur in v0.9?

**Comment by Guilherme5342** [comment]
For now It hasn't happened yet.
