### ISSUE TITLE
Tag Colors: Blue appears purple

### ISSUE THREAD

**Issue by anndee41** [dragonwocky/notion-enhancer#104]
I am using the table view in Notion, and I am editing the colors of my tags (under a "Select" column), and the "Blue" is the same shade as "Purple." There are now two purple colors.

It should be blue, not purple. 

![image](https://user-images.githubusercontent.com/70265305/93587584-b7344980-f9dc-11ea-8541-cb9e3ebf2fae.png)
![image](https://user-images.githubusercontent.com/70265305/93587611-c0251b00-f9dc-11ea-9353-c38f6e58ad44.png)

Windows 10

**Comment by dragonwocky** [comment]
https://github.com/dragonwocky/notion-enhancer/issues/83
