### ISSUE TITLE
Theme "neutral" always in full width in v0.9

### ISSUE THREAD

**Issue by fabiosangregorio** [dragonwocky/notion-enhancer#107]
**describe the bug**
Only in theme "neutral" every page is always in full width even though the option isn't selected. Other themes don't have this bug.

**screenshots**
With neutral theme
![](https://i.imgur.com/aOfNhsp.png)

Wigh gameish theme
![](https://i.imgur.com/B5sY97s.png)

**platform**
Win 10 with notion-enancher v0.9

**Comment by dragonwocky** [comment]
this is intentional.

**Comment by fabiosangregorio** [comment]
I feel like this setting shouldn't be specific of the single theme but should be treated as a separate thing. 
I imagine themes as being a customization of fonts, colors and style, but not something that would impact on the layout of the application. (i.e. I want better colors than the original app, but I don't want to lose the functionality of the full width page)
What do you think about this?

**Comment by dragonwocky** [comment]
the original theme author had a wider normal page, so that's how i left it.
it might be split into a different module in a later release.
