### ISSUE TITLE
I can‘t install notion-enhancer sucessfully anymore

### ISSUE THREAD

**Issue by Georgebush-G** [dragonwocky/notion-enhancer#109]
**what is the bug** :When I use npm command line to install notion-enhancer globally it always reports many errors in cmd. I use scoop to install nodejs globally. The errors say I miss some files, but I really don't know how to fix it except for resetting my computer...

**screenshots**
![image](https://user-images.githubusercontent.com/57062119/93709782-d1546000-fb73-11ea-9163-226d282dbe9b.png)
![image](https://user-images.githubusercontent.com/57062119/93709793-e6c98a00-fb73-11ea-9ff2-86f725688198.png)

**platform**
windows 10

**Comment by dragonwocky** [comment]
can you still launch notion?
what's present in the folder `%localappdata%\programs\Notion\resources`?

**Comment by Georgebush-G** [comment]
> can you still launch notion?
> what's present in the folder `%localappdata%\Programs\Notion\resources`?

I already solve this problem... What I downloaded was a portable version from scoop that has no path in `%localappdata%\Programs\Notion\resources`. Downloading from notion offical website is crucial for this tool...

**Comment by dragonwocky** [comment]
Yes. It is. Scoop is not a supported installation method - if it were, the installation instructions would say so.
