### ISSUE TITLE
Followed all installation steps. No errors. CSS is not working.

### ISSUE THREAD

**Issue by torchatlas** [dragonwocky/notion-enhancer#11]
**describe the bug**
Custom CSS is not appearing in modified Notion

**expected behaviour**
Didn't see any errors in the terminal. I modified a fresh install of Notion, with the latest version of the Enhancer. However, the custom CSS was not working properly.

**screenshots**
![image](https://user-images.githubusercontent.com/12666855/86261311-630f8b00-bb8c-11ea-9616-f490c044ee04.png)

**platform**
Windows 10 v2004

**Comment by dragonwocky** [comment]
are there any errors in the console? (`CTRL+SHIFT+I` to open)

**Comment by dragonwocky** [comment]
what is on line 475 of `%localappdata%\Programs\Notion\resources\app\renderer\preload.js`?

**Comment by torchatlas** [comment]
There is an error coming from fs.js at line 126.

> Uncaught Error: ENOENT: no such file or directory, open 'C:UsersTorch
> otion-enhancer-masteresources${file}.css'

On Line 475 of `%localappdata%\Programs\Notion\resources\app\renderer\preload.js`, is the line
```js
file = fs.readFileSync(\`C:\Users\Torch\notion-enhancer-master/resources/${file}.css\`); // will be set by python script
```
When I replaced that line with:
```js
file = fs.readFileSync(\`C:\\Users\\Torch\\notion-enhancer-master\\resources\\${file}.css\`); // will be set by python script
```
the problem seems to have been pretty much fixed!

**Comment by dragonwocky** [comment]
reopened until the customiser no longer creates this issue

**Comment by dragonwocky** [comment]
does 8dfb764 fix this?

**Comment by torchatlas** [comment]
I ran `cleaner.py` with my previous version, and ran `customiser.py` with the new version. It works!
