### ISSUE TITLE
Blue Select and Multi-Select Properties is purple

### ISSUE THREAD

**Issue by Earth-kun** [dragonwocky/notion-enhancer#110]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
I'm not sure if this bug is caused by notion-enhancer or notion itself. But the color of the properties in multi-select and select that should appear blue, has the color purple instead.

**expected behaviour**
Instead of the property in dateabases having the color blue, it appears to be purple.

**screenshots**
![image](https://user-images.githubusercontent.com/70383964/93732036-2dfe5c00-fc02-11ea-986a-171e9ab4b27a.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
have you updated to v0.9? this was fixed in the latest release.

**Comment by Earth-kun** [comment]
I'm sorry, I didn't notice that there was an update. My bad, thanks for the help!
