### ISSUE TITLE
Weekly calender

### ISSUE THREAD

**Issue by tomvebrcz** [dragonwocky/notion-enhancer#111]
**describe the bug**
Weekly calendar is not working.

**expected behaviour**
Should display only one week calendar. Still showing all month. The app was relaunched many times.

**screenshots**
https://ibb.co/xCHftvb

**platform**
macOS

**Comment by dragonwocky** [comment]
see #101

**Comment by tomvebrcz** [comment]
Hello @dragonwocky,

   this is my page: https://www.notion.so/Bullet-Journal-d3e839d05c644b14b0211d0eccec6a5e
I have found out that the weekly calendar works only when I open it as page not when it's inline.

Can you please check it. 

Thank you.
