### ISSUE TITLE
Can't move new window(ctrl+shift+n) with "tilling window manager mode" checked

### ISSUE THREAD

**Issue by raphapotens** [dragonwocky/notion-enhancer#115]
**bug**
Can't move new window(ctrl+shift+n) with "tilling window manager mode" checked.

**expected**
Move windows freely when holding with ponter the titlebar.

**platform**
Windows 10 2004 (19041.508)

**Comment by dragonwocky** [comment]
no. tiling window manager mode is meant for when windows are handled independently of apps by a window manager (see https://github.com/dragonwocky/notion-enhancer/issues/69).

if you want to be able to move windows normally, don't use tiling window manager mode.
