### ISSUE TITLE
indents are disabled

### ISSUE THREAD

**Issue by alexfeng02** [dragonwocky/notion-enhancer#116]
Summary: Tabbing blocks no longer works while notion is enhanced. 

What currently happen: If I have two default text blocks and hit tab on the second one, it does not indent under the first. 
What should happen: The second block should be intended under the first

Platform: Windows 10

**Comment by autoferrit** [comment]
Same here. hitting <kbd>tab</kbd> works in the browser, or when I disable `notion-enhancer` entirely, it works.

Here, the left darker one is locally with notion-enhancer, and the right is in the browser

![notion-tab-2020-09-23_19 46 56](https://user-images.githubusercontent.com/89895/94095191-0829b080-fdd6-11ea-8891-01dc8b1f2eeb.gif)

Disabling all themes also has no effect.
