### ISSUE TITLE
Page width toggle not working when Notion-Enhancer is installed

### ISSUE THREAD

**Issue by DavidUXer** [dragonwocky/notion-enhancer#118]
Notion-Enhancer is not respecting the page width toggle. Page width is always at "full width" even when full width toggle is set to off. When toggling on and then off, the width contracts for a second and then snaps back to full. 

When I removed Notion-Enhancer, the glitch was eliminated. 

Windows 10

**Comment by dragonwocky** [comment]
@DavidUXer this is a problem with the "neutral" theme that will be changed soon. If you don't want your pages full width, use a different theme until the next release.

**Comment by DavidUXer** [comment]
Ah, good to know. Thanks for the quick reply!
