### ISSUE TITLE
Font chooser erro

### ISSUE THREAD

**Issue by jomiapangilinan** [dragonwocky/notion-enhancer#120]
**The bug**
All types of font under font chooser does not change into desired font style, except for one instance: Times New Roman users who would enter it mistakenly under Sans Serif would be happy with the result.

**Expected behavior and addresses**
I attempted to change the relevant code under the font section of theme.css and inserted the file under 'custom insert' of Enhancements to no luck

**Platform**
Windows 10

**Comment by dragonwocky** [comment]
do you have any other themes/extensions enabled?

**Comment by jomiapangilinan** [comment]
_//this was Segoe UI before_
[style*='Montserrat'] { 
  font-family: var(--theme--font_sans) !important;
} 

[style*='Georgia'] {
  font-family: var(--theme--font_serif) !important;
}
[style*='iawriter-mono'] {
  font-family: var(--theme--font_mono) !important;
}
[style*='SFMono-Regular'] {
  font-family: var(--theme--font_code) !important;
}
_//This is esentially the font style I wanted to try out, I initially just added the font-family code from google fonts and still nada_
[style*='Patrick Hand SC'] {
  font-family: var(--theme--font_cursive) !important;
}

**Comment by dragonwocky** [comment]
I have no idea how you ended up trying this method to change fonts. It seems a mix of a method considerably outdated with some of the current variables, but also is CSS that would never work - the part outside is the selector, which matches something on the page (and so you do not/should not change it), and the part inside is the stying (that's where you would e.g. put in a new font name). The point of the `var`s is that you can change their value without having to worry about the selector.

To do what you're trying to achieve, try this:
```css
@import url('https://fonts.googleapis.com/css2?family=Patrick+Hand+SC&display=swap');
:root {
  --theme_dark--font_sans: 'Patrick Hand SC';
  --theme_light--font_sans: 'Patrick Hand SC';
}
```

Notion does not have an option for a cursive font, and so you must override one of the other styles to add it.

Please check the documentation properly next time.
