### ISSUE TITLE
Hide "Add a comment..." block

### ISSUE THREAD

**Issue by lhecht** [dragonwocky/notion-enhancer#127]
**problem**
For blank pages I am using the property layout function, which works fine. I would like to get rid of the "Add a comment..." line, but I can not find a way to do that. Is it possible to write this into the enhancer?

![image](https://user-images.githubusercontent.com/42421148/94701780-55110800-033d-11eb-8d6f-43f59aaa483b.png)

**solution**
The best possible implementation would be for me, that it does not appear at all on any pages by default. An almost as good solution would be that it is added to the minimized "-> show properties" block. Is that possible?

Thank you very much anyways for your effort and the great tool.

**Comment by dragonwocky** [comment]
https://github.com/dragonwocky/notion-enhancer/blob/master/TWEAKS.md

**Comment by lhecht** [comment]
Hey dragonwocky,

thank you for replying so fast to my question. I am sorry, that I did not find the tweaks before. Maybe one could add a little note to the readme, so that it becomes clear, that there is already a collection of tweaks, that one can look for? 

Cheers
