### ISSUE TITLE
How to call a function defined in a custom-inserts js file

### ISSUE THREAD

**Issue by Micu22** [dragonwocky/notion-enhancer#128]
I need to make a character count for notes.
Until now I was just pasting this code inside the console, and it works fine, but I want to make it more friendly to use.
CURRENT CODE:
```
var mikeMySelector = document.querySelectorAll('.notion-page-content [data-block-id] [contenteditable]');
var mikeAngry = '';

for (var i = 0; i < mikeMySelector.length; i++) {
   var mikeAngry = mikeAngry + ' ' + mikeMyString.item(i).textContent;
}

var mikeResult = mikeAngry.replace(/\s/g,'');
console.log(mikeResult.length);
```

So I wrap it in a function and put in a file which I import using the notion-enhancer module:
`function mike_chars() { CURRENT CODE }`

and then I try to call mike_chars() in the inspect console I get:
> mike_chars is not defined
 
The end result that I am aiming at is to be able to press a shortcut to call a function, but I may also create a UI element in the app that would get real time updated character count.

How can I set the functions so that they can be called?

**Comment by dragonwocky** [comment]
have you tried the word counter module? it already does this and more.

everything is executed in a scope. to make it accessible from global/console assign it to the global namespace: e.g. `window.mike_chars = function () { }` - this is NOT recommended, though. anything that would be calling that function should be placed with it.
