### ISSUE TITLE
Custom Granular Fonts

### ISSUE THREAD

**Issue by Rij29** [dragonwocky/notion-enhancer#129]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**problem**
Just for more customisability and aesthetics

**solution**
I want to be able to select any text in my Notion page and be able to change the font for the same using any custom font on my computer, maybe. 

**alternatives (optional)**
Umm, no, I haven't done this by myself. 
Maybe the math mode can be used for that but I am not exactly sure how that would go.

**Comment by dragonwocky** [comment]
out of scope: there is no reliable way to change fonts per-selected-text without breaking any notion builtin behaviour while also being persisted on reload.

you could possibly make text colour highlighting backgrounds transparent and instead change the font, but that's something you'd need to do yourself with the `custom inserts` module and it's limited to 9 "fonts"/highlights. you can find existing variables that reference highlighted blocks [here](https://github.com/dragonwocky/notion-enhancer/blob/master/mods/core/css/variables.css) and the css selectors that match [here](https://github.com/dragonwocky/notion-enhancer/blob/master/mods/core/css/theme.css).
