### ISSUE TITLE
Make window close button red on hover (and use default cursor on window control buttons)

### ISSUE THREAD

**Issue by torchatlas** [dragonwocky/notion-enhancer#13]
**problem**
The old Notion Customization had:
* a close button that turned red on hover
* window buttons that used the default cursor, instead of the pointer cursor, when the user hovers over the window control buttons, like other apps

**solution**
I implemented this in a few lines of CSS on [my fork](https://github.com/torchatlas/notion-enhancer), and if you're ok with it, I can open a PR for this.
![gcDnZT2pQ1](https://user-images.githubusercontent.com/12666855/86371597-104ad780-bc4f-11ea-9a4a-680a694d987b.gif)

**Comment by dragonwocky** [comment]
looks good, go ahead with opening a PR!
