### ISSUE TITLE
Windows Installation Failing

### ISSUE THREAD

**Issue by archetyped** [dragonwocky/notion-enhancer#131]
**describe the bug**
Installation fails when running `npm i -g notion-enhancer` with the message:
> Failed at the notion-enhancer@0.9.1 postinstall script.

(see below for full output)

**expected behaviour**
Notion Enhancer should be installed.

**terminal output**
```bash
C:\Users\TheUser\AppData\Roaming\npm\notion-enhancer -> C:\Users\TheUser\AppData\Roaming\npm\node_modules\notion-enhancer\bin.js

> node bin.js apply -y

C:\Users\TheUser\AppData\Roaming\npm\node_modules\notion-enhancer\node_modules\fs-extra\lib\mkdirs\make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\TheUser\AppData\Roaming\npm\node_modules\notion-enhancer\node_modules\fs-extra\lib\mkdirs\index.js:3:44)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! notion-enhancer@0.9.1 postinstall: `node bin.js apply -y`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the notion-enhancer@0.9.1 postinstall script.
```

**platform**
* OS: Windows 10 Pro
* Terminal: Tested in both CMD and PowerShell (run as standard user and as administrator) with same results.

**Comment by dragonwocky** [comment]
what version of node.js do you have? (run `node -v`)

you need a version higher than 10.3.0 to prevent this error.

**Comment by archetyped** [comment]
I was able to install notion-enhancer via WSL, which has node v14.3.0.

I believe node.js on Windows was v8 , but I uninstalled it in order to update it to a more current version.

I'll test again once I have a newer version of node.js installed on Windows and post an update if there are still issues with installation.

Thanks.
