### ISSUE TITLE
Themes not working

### ISSUE THREAD

**Issue by archetyped** [dragonwocky/notion-enhancer#132]
**describe the bug**
None of the themes aside from "Dark+" are applied when enabled. 

Steps:

1. Enable single theme (all other themes are disabled).
2. Restart Notion app.

Notes:

* Tested with Notion's own Dark Mode enabled and disabled.
* littlepig dark: Theme's font colors appear to be applied, but that's it.

**expected behaviour**
Appearance should match screenshot of theme on [notion-enhancer's home page](https://dragonwocky.me/notion-enhancer/). 

**screenshots**
![Notion_Enhancer_Issue_Themes-not-applied](https://user-images.githubusercontent.com/3237917/94743110-8cb68a80-0312-11eb-8062-34fd00e7d87c.png)

**platform**
* OS: Windows 10 Pro

**Comment by dragonwocky** [comment]
@archetyped are there any errors in the console of either menu or app (`ctrl+shift+i` to open)?
if you reload the menu, does it still say the theme is enabled?

**Comment by archetyped** [comment]
No errors in console for either app or menu.

How do I reload the menu?  If you mean close and reopen it from the system tray, then yes, it still shows the theme as enabled.

**Comment by dragonwocky** [comment]
are any other extensions enabled? does this happen with any of them or is it purely a themes issue?

**Comment by archetyped** [comment]
Looks like there was something wonky with the WSL install (Node v14.3.0/NPM v6.14.5), as `notion-enhancer/mods` was missing several folders.

I uninstalled Notion Enhancer, updated Node/NPM for Windows (Node v12.18.4/NPM v6.14.6), and then reinstalled Notion Enhancer via PowerShell instead.

All themes load properly now, except that it turns out that none of themes are for me 🤷‍♂️ 

Not sure why the WSL install went sideways, but I'll post an update if I ever find out.

Thanks for the help.

**Comment by dragonwocky** [comment]
weird, I've never had issues with WSL. least it's working now.

but hey - if none of the themes fit your preference, try [making your own](https://github.com/dragonwocky/notion-enhancer/blob/master/DOCUMENTATION.md).

**Comment by archetyped** [comment]
> but hey - if none of the themes fit your preference, try [making your own](https://github.com/dragonwocky/notion-enhancer/blob/master/DOCUMENTATION.md).

Indeed, that was my next step! Thank you for the link to the docs.  I checked the wiki for pointers, but did not check the code itself.
