### ISSUE TITLE
Bypass Preview: Page not fully closed when navigating back with keyboard/mouse back button

### ISSUE THREAD

**Issue by archetyped** [dragonwocky/notion-enhancer#134]
**describe the bug**
Love the "bypass preview" option, but I recently noticed that pages were unresponsive for some reason when navigating back to a previous page via the keyboard shortcut (`ctrl + [`) or the back button on a mouse.  It look like pages step backward into modal view (but are invisible) when navigating back to the previous page using either of these methods.

With the invisible modal page overlaying the current page, interaction with the underlying page is prevented until you click on an area of the window outside of where the modal page would be (e.g. click on left or right edges of window), as this appears to close the modal window.

In fact, the invisible modal pages can even be interacted with if you get lucky while clicking around in the central area of the screen (where the modal page would be).  For example: displaying the options of a select field of a DB record.

**steps to reproduce**

* Enable "bypass preview" option
* Open a page in Notion
* Navigate back to previous page in Notion via keyboard shortcut (`ctrl + [`) or back button on mouse.
* Attempt to scroll current page - No response from page.
* Click on left or right edge of window (outside of where modal page would be) - Underlying page can now be scrolled, etc.

**expected behaviour**
Previous page should be fully accessible after navigating back with keyboard/mouse button without further clicks, just as when navigating back using the back arrow in Notion's UI.

**screenshots**
N/A - no screenshots for invisible modal page.

**platform**
Windows 10 Pro

**Comment by seltzdesign** [comment]
Having the same issue on MacOS 10.15. If you go back using cmd - [ the page is unresponsive and the content of the previously opened page is still there invisibly. Using the back icon it works, but using the shortcut (mapped to a mouse button) it does not. I also noticed the Notion Helper process shoots up to 90% CPU in that case.

If you drag on the scrollbar it's unresponsive the first time, then the second time the page comes back to normal.
