### ISSUE TITLE
Manjaro i3 -> Notification Area Icon Missing (ie. Can't customize)

### ISSUE THREAD

**Issue by joshuajz** [dragonwocky/notion-enhancer#135]
**describe the bug**
When notion and notion-enhancer are installed on linux with a tiling window manager, there is no notification icon that allows the user to modify Notion's settings.  I have installed notion-enhanced because my scroll bar and the top bar have both changed.

**expected behaviour**
Every other version of notion-enhancer has the notification icon as a way to edit the settings for the program.

**platform**
Manjaro with the i3 window manager

I realize that the amount of users that this effects is probably low, but thanks for looking into it!

**Comment by dragonwocky** [comment]
@joshuajz this is a system limitation on your side, not something I can fix. You can still open the menu with `ALT+E`, though.
