### ISSUE TITLE
Something Wrong with the window button

### ISSUE THREAD

**Issue by Septem-YDL** [dragonwocky/notion-enhancer#136]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
Something Wrong with the window button

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
![image](https://user-images.githubusercontent.com/71010871/94996998-bbff1d00-05da-11eb-814f-ea935c30c87c.png)

**platform**
Windows 10 2004
Surface pro 3

**Comment by dragonwocky** [comment]
@Septem-YDL are you behind a proxy/vpn by any chance (e.g. a school network)?

**Comment by dragonwocky** [comment]
this looks like a duplicate of https://github.com/dragonwocky/notion-enhancer/issues/66

**Comment by Septem-YDL** [comment]
Yes，i was behind a vpn.
today it runs normally 😂
