### ISSUE TITLE
Remappable Keyboard shortcuts

### ISSUE THREAD

**Issue by sghsri** [dragonwocky/notion-enhancer#137]
**problem**
A lot of the keyboard commands within notion don't seem to fit with common browser or code editor commands that I'm familiar with. An example of this is since I'm using the enhancement that removes previews, I think it would be nice to have the "esc" key still go up one level when viewing a page.  Currently, there's no way to remap keyboard shortcuts or even map my own to certain actions. 

**solution**
I think giving people the ability to remap common actions or even the entire suite of notion actions would be very helpful and improve on something that a lot of people deal with.

**Comment by dragonwocky** [comment]
can't be done: all of notion's keyboard shortcuts are handled by scoped event listeners and most of what they do involves manipulation of page data that the enhancer can't reliably replicate.

keyboard shortcuts added by the enhancer already can be configured.
