### ISSUE TITLE
Default Full Width and/or small text for all Pages.

### ISSUE THREAD

**Issue by sghsri** [dragonwocky/notion-enhancer#139]
**problem**
I personally set all my pages to be full width so I can see as much as possible on a certain page. The problem is that Notion doesn't have default settings so for every new page we have to set them separately. 
![image](https://user-images.githubusercontent.com/13592854/95122572-53b55600-0716-11eb-8d42-743ecdaaf2d4.png)

**solution**
It would be great to be able to set the default settings within the enhancer that should be applied to all new pages that are created.

**Comment by dragonwocky** [comment]
it won't change the actual setting, but you can make all pages appear full width by adding the following with the custom inserts plugin:
```css
:root {
  --theme_dark--page_normal-width: 100%;
  --theme_light--page_normal-width: 100%;
}
```

**Comment by safwaan-menk** [comment]
> it won't change the actual setting, but you can make all pages appear full width by adding the following with the custom inserts plugin:
> 
> ```css
> :root {
>   --theme_dark--page_normal-width: 100%;
>   --theme_light--page_normal-width: 100%;
> }
> ```
> 
> most of the enhancer's functions are just visual. it can't reliably modify actual page/account data yet.

How do we download the copy inserts plugin?

**Comment by dragonwocky** [comment]
@safwaan-menk all mods come with the notion-enhancer when you install it. The custom inserts and tweak's mods have since been merged, though - now you can upload your custom CSS file to the `css insert` option under the tweaks extension.

**Comment by safwaan-menk** [comment]
> @safwaan-menk all mods come with the notion-enhancer when you install it. The custom inserts and tweak's mods have since been merged, though - now you can upload your custom CSS file to the `css insert` option under the tweaks extension.

If I create a css file with only the below code, which you gave, would it achieve the full width facade?

`
:root {
  --theme_dark--page_normal-width: 100%;
  --theme_light--page_normal-width: 100%;
}
`

**Comment by dragonwocky** [comment]
@safwaan-menk probably not, the css variables available for customisation have changed. This issue thread has been closed for over 2 years, so it's very outdated. You can find the full list of available variables and their default values in this CSS file that you can customise as you like, though some of them aren't working perfectly at the moment due to Notion updates: https://github.com/notion-enhancer/repo/blob/9c869179b39dc11e07d6b6200b3ebd8d344cde16/theming/variables.css
