### ISSUE TITLE
Neutral theme: Text clipping when closing sidebar

### ISSUE THREAD

**Issue by tsweezy** [dragonwocky/notion-enhancer#143]
**describe the bug**
When the sidebar is closed using the Neutral dark theme, what looks like I can only describe as a 'footer' appears at the bottom of the window. It's animated and appears to also push the scrollbar up when it appears. Rollovers for the now hidden text behind the 'footer' appear in front of it. If this was intentional, my mistake—it just doesn't appear that way to me.

**expected behaviour**
With the sidebar open, the text continues to the very bottom of the window before being clipped by the the bottom of the frame, like normal. When it's closed, I would expect the same behavior, as with vanilla Notion and other themes.

**screenshots**
![video](https://user-images.githubusercontent.com/45302428/95399213-abe68680-08d5-11eb-9f29-5a29f54a2fd1.gif)
Showing default theme first, for reference.

**platform**
Windows 10

**Comment by dragonwocky** [comment]
ah, yeah, that should have been moved into the focus mode extension, thanks for letting me know
