### ISSUE TITLE
Able to choose a default option for Show/Hide properties in database pages

### ISSUE THREAD

**Issue by Rij29** [dragonwocky/notion-enhancer#144]
**What I want?**
Hey, I love that I can show/hide the properties in database pages but I would love it if I could choose a default option of always opening with properties shown or hidden. Right now the default is hidden on start up, I would love to have the other option as well keeping the Hide properties tab open.

**Why?**
I would just like it for a choice and personally smoother experience.

**Comment by dragonwocky** [comment]
would this default be global or per-page?

**Comment by Rij29** [comment]
I would be happy with just a global default!

**Comment by Rij29** [comment]
Or it could also be nice to be able to choose that for different databases that we are using depending on the informations that's important.

**Comment by dragonwocky** [comment]
i'll start with a global one... per-page settings will probably come for most things in the future, but I'm building the features bit-by-bit

**Comment by Rij29** [comment]
Yeah, that's great! Thanks!

**Comment by dragonwocky** [comment]
similar things would be good to do with a few mods, so moving this to one issue to track them all.
