### ISSUE TITLE
dracula theme readability

### ISSUE THREAD

**Issue by dragonwocky** [dragonwocky/notion-enhancer#146]
![image](https://user-images.githubusercontent.com/16874139/95569936-f997f600-0a71-11eb-8e69-a59cc3ddd6f0.png)

card colour is too bright, text on grey backgrounds is too dark, and some characters just straight up aren't visible in code blocks

**Comment by dragonwocky** [comment]
@mimi-shahzad it won't let me assign you to the issue until you comment here, but this is a ping to make sure you see it - the dracula theme needs a bit more work, thanks!

**Comment by dragonwocky** [comment]
@mimi-shahzad also, are you in the [discord](https://discord.gg/sFWPXtA)? if not it'd be good if you could join to keep up to date with what's going on with the enhancer and be contactable, if you are could you ping me and let me know your name so i can give you the contributor role?

**Comment by mimi-shahzad** [comment]
@dragonwocky I am now as mimishahzad386#5651. Sorry I haven't been responsive, I could've sworn I had this on notif but I guess not. I'll edit the theme a bit more, sorry for the delay.

**Comment by mimi-shahzad** [comment]
I opened a new PR by the way, just letting you know. I hope you had a great weekend, and let me know if I should change anything else. Thanks~

**Comment by dragonwocky** [comment]
Hi @mimi-shahzad, thanks for the changes. After testing though I reverted the commit because while it had fixed a couple of things (though not all the ones I'd listed) there were a few other colour changes (e.g. text in the sidebar and text on blue backgrounds) that you seem to have mixed up with something else and looked really out of place.

To be clear, the theme shouldn't be changed from how it is now except:
* the sidebar/dragarea background colours should be slightly different from the main content (a little darker or lighter).
* text on grey backgrounds (only grey) should be white.
* card colour (the bright blue behind the mod options in the screenshots above) should be darker.
* punctuation characters in code blocks should be grey or white: at the moment they are the same colour as the background (pictured in the first message).

If you could have a go at those from the current state of the theme in this repo that'd be great.
