### ISSUE TITLE
Design Issue - Board View

### ISSUE THREAD

**Issue by marcovrj** [dragonwocky/notion-enhancer#147]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
There are arrows surrounding the columns in Board views in Windows App. 
There is a color change in Board View in box with a black grey.

**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/54723662/95605015-bd8f7180-0a2e-11eb-828a-54e3e076f71d.png)
![image](https://user-images.githubusercontent.com/54723662/95605323-2f67bb00-0a2f-11eb-8ee1-5a278a22a170.png)

**platform**
what OS are you using? Windows app in Windows 10.

**Comment by dragonwocky** [comment]
https://github.com/dragonwocky/notion-enhancer/issues/126
