### ISSUE TITLE
Notion doesn't open, have to shut down and open again

### ISSUE THREAD

**Issue by serjanbiogenic** [dragonwocky/notion-enhancer#148]
**describe the bug**
1. go full screen with Notion, then click on X to close the app - I only see black screen (Notion app is still in the dock) 
2. command + Tab to switch from black screen to desktop (to escape black screen)
3. Notion app is till in the dock, but clicking on it doesn't do anything unless I hit Command + Q to quiet the app completely

Same behaviour of the app not opening happens without going full screen too. 

**expected behaviour**
app should open when you click on it 

**platform**
Mac 10.15.7

**Comment by dragonwocky** [comment]
see https://github.com/dragonwocky/notion-enhancer/issues/113 for an explanation and a way to disable this
