### ISSUE TITLE
max width of columns is too big

### ISSUE THREAD

**Issue by Malainfluencia** [dragonwocky/notion-enhancer#149]
**problem**
always frustrates me !

**solution**
please let the width of the columns be customizable  =(

**Comment by dragonwocky** [comment]
https://github.com/dragonwocky/notion-enhancer/blob/master/TWEAKS.md#table-columns-below-100px

**Comment by dragonwocky** [comment]
rereading this i may have misinterpreted it: is that link helpful or are you referring to something else?
