### ISSUE TITLE
I cant Upgrade to v6 from v5 in Notion enchancer

### ISSUE THREAD

**Issue by alcoranpaul** [dragonwocky/notion-enhancer#15]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
When I update Notion enhancer from v5 to v6, it instead downgrades.

**Methods I used**
I first closed Notion I then ran the cleaner.py then ran the new customizer.py and then when opening notion, It downgrade to normal notion without the cleaner Scrollbar on the side and stuff. But when upgrading to v5, it still works

**platform**
I use windows 10 2004

**Comment by dragonwocky** [comment]
what log output does v6 have?
when you go to `C:\Users\vinetom\AppData\Local\Programs\Notion\resources`, what files are present?

**Comment by alcoranpaul** [comment]
Hello, this week was a very busy week for me sorry for the inconsistency about this issue.
 Thank you for your patience

The files are:
app (folder)
app.asar.bak
app-update.yml
electron.asar
elevate (application)

**Comment by dragonwocky** [comment]
does this issue persist with v7?
(making sure the app is completely shut down with no notion tasks in task manager)

**Comment by alcoranpaul** [comment]
v7 fixed it :)
Thank you for time and effort for helping me and upgrading Notion 👍
