### ISSUE TITLE
Tray icon not showing up on Fedora notion-app. Unable to restart application.

### ISSUE THREAD

**Issue by juliapacula** [dragonwocky/notion-enhancer#150]
**describe the bug**
When having an option "close window to the tray" it does not create tray icon, therefore I cannot reopen the application.

Also, I am not sure if it is notion-enhancer bug or notion-app for Linux, but after closing an app I am unable to reopen it (it says it has an auto-updater issue, [there is already issue for that in notion-app repostory](https://github.com/jaredallard/notion-app/issues/11). I thought maybe you could come up with a fix for that).

**expected behaviour**
When option "close window to the tray" is turned on, there should be a tray icon in my system.

**screenshots**
There is the error that is given after closing the application:
![image](https://user-images.githubusercontent.com/22871925/95649997-13245680-0ae1-11eb-8835-10da3bde2ecc.png)
I have no screenshots of bug connected with tray icon, because it just does not appear :blush: Any help would be appreciated!

**platform**
Fedora with linux notion-app.

**Comment by dragonwocky** [comment]
do tray icons for any other apps show up? some linux window managers just don't support electron tray icons, there's nothing i can do about that.

you should be able to reopen/toggle the window with the `ctrl+shift+a` keyboard shortcut.

**Comment by mr-islam** [comment]
Oh hey, I was just talking about this on the Discord as well. I can confirm I have the exact same issue as described above by Julia.

@dragonwocky How can we update the app? I tried compiling `notion-app` using the latest Notion 2.0.8 mac release and had the same issue…

**Comment by dragonwocky** [comment]
The latest release is 2.0.9, not 2.0.8

**Comment by dragonwocky** [comment]
hm, i'm not really the right person to ask then: i know there is a 2.0.9 but apparently not for mac. only thing i can suggest is to try creating a file at the location `/opt/notion/app/dev-app-update.yml` with this content:
```yml
provider: generic
url: 'https://desktop-release.notion-static.com/'
channel: latest
```

**Comment by juliapacula** [comment]
Responding to your question: yes, other tray icons show up. Previously I was using notion with nativefier and I was able to create tray icon for this one.

Thank you for the tip with shortcut, it is really helpful :blush: 

And going back to the `dev-app-update.yml` file, now i get different error:

![image](https://user-images.githubusercontent.com/22871925/95655863-9efea880-0b0a-11eb-88db-ebfb745c7289.png)

I tried killing proccesses and launching notion via terminal and I was able to get more detailed info about autoUpdater:
```
15:11:29.955 › Error: Error: Cannot find channel "latest-linux.yml" update info: HttpError: 404 
"method: GET url: https://desktop-release.notion-static.com/latest-linux.yml?noCache=1ek9a6f72\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
```

**Comment by juliapacula** [comment]
Okay, now I understand why it is not working... A small brain lag occured and I forgot notion-app is efectivelly creating linux application from dmg, but there is no official app for notion. I think the only solution is to remove auto-updater. So I will just wait for the second issue to get resolved, thanks for help with this one!

But still wondering why electron tray icons are not working :thinking:

**Comment by dragonwocky** [comment]
Not sure. Seems like its a platform-specific bug, but I don't have a fedora install I can test on at the moment and debugging remotely is a pain, so if you can just make do the the shortcut for now that'll have to do.

**Comment by dragonwocky** [comment]
@juliapacula @mr-islam a fork of the deb builder has been made that works with the enhancer (and will hopefully be merged into the main repo soon!) - https://github.com/haydn-jones/notion-deb-builder

**Comment by mr-islam** [comment]
@dragonwocky Successfully installed using the fork, enhancer along with the tray icon work perfectly :+1: 

@juliapacula and any future reader: This is how I was able to install notion-enhancer on Linux using the updated notion-deb-builder:

1. Setup 
    1. Uninstall any previously installed Notion builds (I recommend double checking the local and system-wide applications folders to make sure)
    1. Downloading the `build.sh` script from https://github.com/haydn-jones/notion-deb-builder
    2. Downloading notion windows from the official website (to the same folder as above), rename it to be `notion.exe`
    3. Ensuring I have all the build dependencies as mentioned on line 39 of the script (I needed to install `asar electron-packager electron-installer-debian` from npm, and I installed them globally out of laziness) 
2. Notion Build & Install 
    1. Running `./build.sh win`
    2. After some time, the deb will be ready in a new `out` folder
    3. Install as you like
3. Enhancer - following the usual steps as listed in this enhancer repo to install 
    1. Install enhancer globally from npm
    1. Close any running instances of Notion on the system (2x check with a task monitor)
    1. Use it to `check` and ensure there is no remnants of any past attempt (if it finds anything, do a `remove`)
    1. Finally, `apply` (I think I needed to run it with `sudo`) and it will be ready
    1. Open Notion and enjoy

As for doing the same for an rpm build, the difference will come in the 1st and 2nd parts of the process above – I think you will need to check the [notion-rpm-builder repo's build script](https://github.com/utkarshmalik211/notion-rpm-builder/blob/master/build.sh) and change it to match with the fork of the deb builder made by @haydn-jones (just a few lines that make sure an asar is created) and the rest of the script should be fine. Or the reverse works too like @juliapacula mentioned: changing the forked deb script to make an rpm.

Or if I was on an rpm-based system, I would take the laziest way out: creating a deb and then converting that to an rpm 😉️

**Comment by dragonwocky** [comment]
@juliapacula please let me know if this is working for you, + whether the tray icon is shown or not.
