### ISSUE TITLE
night shift not allowing dark mode on macOS

### ISSUE THREAD

**Issue by dragonwocky** [dragonwocky/notion-enhancer#151]
https://dsc.cloud/a7f386/Screenshot-2020-10-10-at-18.58.42.mp4

see relevant discussion/proof on discord: https://discordapp.com/channels/748161877045149706/748162434237202472/764443865947176980

**Comment by cookandy** [comment]
I'm also noticing the same.

Notion version `2.0.8`, Enhancer version `0.9.1`.
