### ISSUE TITLE
Increasing readability by tweaking line-height and margin-top in text blocks

### ISSUE THREAD

**Issue by Arecsu** [dragonwocky/notion-enhancer#155]
Notion's default readability in text blocks is, in my opinion, **really bad.**
Very compressed. Little white space. I find it hard to have a good reading experience.

Let's take a look at these screenshots:

### Default 😷
![image](https://user-images.githubusercontent.com/12679098/95767275-e4e27a80-0c8a-11eb-8d85-02c39d0c9778.png)

### Tweaked 🥰
![image](https://user-images.githubusercontent.com/12679098/95767567-4d315c00-0c8b-11eb-8d8c-0c1452b978f8.png)

Second one looks much more easier to the eye.

Of course, this is subject to personal preference and, also, will depend on font selection and font sizes.
I was thinking in adding this specific settings to my theme Neutral, but I think every theme should benefit from a custom variable in `theme.css`.

**So, I propose to add a variable like `--theme--text-block_margin-top` and `--theme--text-block_line-height` to be able to achieve what I did on the second screenshot.**

Then, each theme mantainer or a mod could make use of these variables to further tweak text readability.

### Class
`.notion-selectable.notion-text-block`

### Properties
`line-height` and `margin-top`

I'm not sure if being able to edit all the margins make sense, given that `margin-left` and `margin-right` are kind of _pointless_ to tweak and `margin-bottom` is not a "good practice" given that headings have margins at the top. So, it would be more consistent to change the value of `margin-top` as well.

**Comment by dragonwocky** [comment]
hm, i've been thinking of creating a "common tweaks" mod that'll have things a few of the things from the tweak docs etc.
just considering whether a spacing/layout change should be part of a theme or part of that? then it could be mixed/matched with any theme or if somebody prefers the default then they would still be able to use your theme without the extra spacing.

**Comment by Arecsu** [comment]
Maybe "color schemes" could be a thing. And making a UI so just one color scheme is enabled. The rest of the changes could be split across other mods/user tweakable mods.

Aside from that, the complexity and probability of "conflicts" between some mods and color schemes will eventually increase I guess. making it kind of a problem with the user activating certain mods and not seeing changes or breaking something.

The "easiest solution" I can imagine would be to order the enabled mods in priority, so if there's some mods that conflicts in variables with each other, the one at the top will get priority and that's the one who's going to get the value in the variable.

I can see some caveats from it, like complex javascript stuff that ends up controlling the same function that other mod does. How can this be prevented? This could be "fixable" by proper mantaining of the codebase, but I don't find that solution very elegant.

Other solution that comes to mind is flag mods and "color schemes" as "conflicted" with other ones if that applies. For example, if the Neutral theme ends up being splitted into Color Scheme, Layout and Typography, I can see the "Typography Inter mod" conflicting with the one adds the option to the user to decide between the fonts installed in their computer.

I could flag that one as "conflicts with 'font chooser'" and viceversa, so the user and notion-enhancer can take proper actions in that regard.

**Comment by dragonwocky** [comment]
The "conflicts with:" alert is a good idea, and conflicting mods could be outlined red and brought to the top of the menu. Mods will be re-orderable in the next update, which will help with that too.

Having too many different types of extensions increases complexity, both of the user interface and of the loading process. I'd rather not go down that path. In effect, themes encompass colour schemes and extensions encompass layout (additions to and changes of). It might be helpful though to add more descriptive tags to things along the lines of that.
