### ISSUE TITLE
Installing enhancer causes Notion to display Korea 

### ISSUE THREAD

**Issue by z-jason** [dragonwocky/notion-enhancer#157]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

Using Notion 2.0.8. Once I installed the enhancer, Notion display all menu text in Korea. I confirmed that the language is set to English. As soon as I remove the enhancer, Notion display English menu properly.

**expected behaviour**
why is this a bug - what should be happening?

The menu text should be displayed in English.

**screenshots**
https://cln.sh/TGx1Cs

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

Mac OS

**Comment by dragonwocky** [comment]
does this happen on every launch? usually this only happens when i've been messing with a lot of settings and then only reload instead of relaunching.

**Comment by dragonwocky** [comment]
closing until @z-jason responds to this or someone else has the same problem
