### ISSUE TITLE
Option for databases to choose whether to open page full screen or just preview.

### ISSUE THREAD

**Issue by szutsattila** [dragonwocky/notion-enhancer#158]
**problem**
For some tables I need to just inspect items (just the name and few properties) like tasks db, for others there is content that is more important, like notes. It would be great if I could change the setting of bypassing preview for each db (like with auto collapsing properties).

**solution**
A setting for db-s where I can toggle this setting (like with pages: full-width, small text, etc.).

**alternatives (optional)**
Maybe first implementing a global setting that does not require restart and then moving it to the three dot menu below for example page lock.

**Comment by dragonwocky** [comment]
similar things would be good to do with a few mods, so moving this to one issue to track them all.
