### ISSUE TITLE
[Request] Fix overly restrictive URL parameter

### ISSUE THREAD

**Issue by nihaals** [dragonwocky/notion-enhancer#160]
I've already implemented this change (it's a single line edit in `main.js`) but I'm not sure how to add it to notion-enhancer. I am referring to the section that checks for the custom URL protocol:
```js
if (process.platform === "win32") {
    const url = argv.find(arg => arg.startsWith(config_1.default.protocol + ":"));
    const urlPath = url && makeRelativeUrl(url);
    handleActivate(urlPath);
}
```
This can actually be used on *any* platform and doesn't need to be restricted to Windows. This is especially useful for https://aur.archlinux.org/packages/notion-app as it can support the custom URL protocol with this change.

See [this comment](https://aur.archlinux.org/packages/notion-app/#comment-770514) for more info

**Comment by dragonwocky** [comment]
I followed what it said in the comments on the AUR, but re-reading this now you've said it'll work with any platform? Does that include macOS?

**Comment by nihaals** [comment]
I see no reason why not (but I haven't tested it). I can partially see why this platform check is here: I believe macOS uses native code as the handler for custom protocol handlers so a CLI arg is not needed for that platform, but as people wouldn't really be accidentally starting Notion with arguments, I think it solves a problem that doesn't exist (so letting it work on all platforms, even ones that don't necessarily need it should be fine).

Another possible patch could be to let it work without an instance of Notion already running. I haven't tried starting the first instance with a URL yet but judging from the code it only opens the URL if there's already an instance open. As there are more URLs than OAuth callbacks, allowing this could be useful. It may be that they added this check as you might lose the page Notion was on before you closed it last but then you could:

- Continue starting the instance with the previous page but then also start a new instance with the passed in URL (when you have no instances open and you start one with a URL it would actually start 2 instances)
- Start the instance like normal but after it's loaded, open the passed in URL. I believe the back button would work here so you could return to what you had open last time through that

(These would only affect the first instance, any after that can act the way they do now which is just start an instance that opens the URL

**Comment by dragonwocky** [comment]
You can open a Notion URL over the `notion://` protocol without there already being an existing instance - there's another handler on line 88 in `main/main.js` that's called for new instances.

**Comment by jamezrin** [comment]
Thank you so much @dragonwocky and @nihaals. Looking forward to v0.10.0!

**Comment by dragonwocky** [comment]
@davidbailey00 while you're here: does this also work with the deb builder?

**Comment by davidbailey00** [comment]
Yes this works! Not sure if it's related, but there seems to be an issue with the custom titlebar after first login using this method (although not after relaunching the app):

![image](https://user-images.githubusercontent.com/4248177/101386522-3850fd80-38b5-11eb-9fde-fddc09763d36.png)

**Comment by davidbailey00** [comment]
Yes this works! Not sure if it's related, but there seems to be an issue with the custom titlebar after first login using this method (although not after relaunching the app)
