### ISSUE TITLE
Vim mode

### ISSUE THREAD

**Issue by dlagg** [dragonwocky/notion-enhancer#162]
It will be very nice to enable a vim mode, in fact, if you use a vim mode extension for the browser and visit notion.so you got it.

I think the implementation should be very similar to browser extensions, with classics vim keys, modes and "sneak mode" ,'f' key in [Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb) included.

**Comment by dragonwocky** [comment]
I can't make this. I've never used Vim, so honestly it just doesn't make any sense to me (especially since most of the shortcuts appear to be just normal characters - does not that e.g. interfere with typing?).

If you or someone else wants to try this, the developer documentation and contributor guidelines are there, go ahead.

**Comment by dlagg** [comment]
> I can't make this. I've never used Vim, so honestly it just doesn't make any sense to me (especially since most of the shortcuts appear to be just normal characters - does not that e.g. interfere with typing?).
> 
> If you or someone else wants to try this, the developer documentation and contributor guidelines are there, go ahead.

Vim uses different modes, Normal mode (shortcuts and navigation), insert (typing) or visual (selection) so there is no interference.
Yes seems little bit harder to implement, maybe I could try it when I have free time. Here I leave the request in any case.

**Comment by Syn-Tax** [comment]
As a vim user this would be my one feature request which I would be happy to work on if no one else is yet. I don't know if the "sneak mode" is necessary as notion has built in functionality to change pages with the keyboard which could either be remapped for vim users or just kept as is. Anyway if no one else is working on it I can.
