### ISSUE TITLE
Responsive Layout

### ISSUE THREAD

**Issue by pranjalshah9814ps** [dragonwocky/notion-enhancer#168]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**problem**
I frequently work with Notion off to the side taking around ⅓rd of my laptop screen. However, when multi-column pages are open, instead of the columns rearranging to a single column as on mobile, they just get squashed which is frustrating since nothing is readable.

**solution**
Make the Notion window responsiveness i.e. it converts to a single column view like on mobile once a certain breakpoint has been reached.
This Chrome extension does exactly this: https://chrome.google.com/webstore/detail/notionso-faster-responsiv/leadcilhbmibbkgbnjgmmnfgnnhmeddk. I'm not a technical guy so I don't know how it works but this seems like something that would greatly improve the Notion Enhancer experience.

**alternatives (optional)**
Matheus Cezar has created a Chrome extension which opens a responsive Notion popup window. Here is the link to the GitHub project: https://github.com/matheus6417/notion.so-responsive-chrome-extension

**Comment by dragonwocky** [comment]
already done in the work-in-progress build.

**Comment by fabiosangregorio** [comment]
Hi @dragonwocky, it's me again :)

I use Notion on my surface, and I often use it in half-width so I can have another window open on the side. The responsive mode starts at 1/3 of width though, so I still see everything squashed, like in the screenshot below.

![](https://i.ibb.co/c1pkhpD/image.png)

Would it be possible to add a configuration option for the start of the responsive mode, or something like that? What do you think?

**Comment by dragonwocky** [comment]
@fabiosangregorio added, give that a go.

**Comment by fabiosangregorio** [comment]
@dragonwocky this works beautifully. Thank you very much!
