### ISSUE TITLE
Uninstall instructions

### ISSUE THREAD

**Issue by citydelver** [dragonwocky/notion-enhancer#169]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**problem**
There are no clear instructions for uninstalling. I had to uninstall (version 0.6.1, which required not only Node.JS but also Python to be installed in Windows). Running cleaner.py didn't do anything (it simply didn't find the two files it looked for and the script stopped there), and its only mention is to "remove older versions", so maybe it simply does not remove the version it was installed with, I don't know.

**solution**
There should be (per version) instructions for uninstalling as clear as those for installing.

**alternatives (optional)**
Better yet, there could be an automatic full uninstallation script/tool...

**Comment by dragonwocky** [comment]
While in rapid development (until v1.0.0) no support is provided for versions pre-current other [how to get from an old version to the most recent](https://github.com/dragonwocky/notion-enhancer/blob/master/UPDATING.md).

Node.js and Python are both separate programs that have their own uninstallation instructions.
`cleaner.py` has never said anything about "remove older versions," so I don't know what you're doing there. If you haven't got it figured out yet, the simplest way is to just uninstall/reinstall Notion.

Uninstallation instructions for the latest version do exist.
