### ISSUE TITLE
Notion Enhancer GUI

### ISSUE THREAD

**Issue by torchatlas** [dragonwocky/notion-enhancer#17]
**problem**
With the growing number of options for Notion Enhancer, a GUI would be helpful
It would also allow for more types of options, and more features, like a theme creator

**solution**
I'm not sure if it'd be implemented as an ElectronJS window, or a Python GUI, but whatever works

**alternatives (optional)**
Add Notion Enhancer settings to Notions's Settings screen

**Comment by dragonwocky** [comment]
already planned as part of #6
theme creator not likely any time soon, but making themes/plugins will become way easier than they are at the moment

**Comment by dragonwocky** [comment]
discussion moved to #6 to clean up issues
