### ISSUE TITLE
Prevent disappearing of submenu on hover

### ISSUE THREAD

**Issue by fabiosangregorio** [dragonwocky/notion-enhancer#171]
**problem**
The most frustrating thing of Notion is when:
1. you open a menu (database properties, block options, etc)
1. then you hover on a menu item to open the submenu
1. you move the cursor on the first item of the submenu and the submenu disappears. 

So you have to re-open it and make sure you move the cursor along the menu item to enter the submenu.

I don't know if I explained myself. Here's an example from the discord server:

![](https://media2.giphy.com/media/ymxUx9wDwci2pG6Ipo/giphy.gif)

**solution**
It would be awesome if this could be fixed, maybe adding a delay in the disappearing animation or something like that. What do you think?

**Comment by dragonwocky** [comment]
I can't replicate this... even when I move my mouse away from the colour select menu it doesn't disappear like that.

Even if I could I'm not sure if I could fix it - it's managed by Notion's editor JS that's scoped and out of my control without breaking a whole lot of other stuff. Changing CSS rules don't help much if the element doesn't exist anymore.

Closing this one, but your other comments have been very helpful! Keep it up.
