### ISSUE TITLE
Cards and switches lack contrast in Neutral theme

### ISSUE THREAD

**Issue by fabiosangregorio** [dragonwocky/notion-enhancer#175]
Hi @dragonwocky :)

I feel like cards and switches lack contrast in Neutral theme. Take a look at these examples: the card doesn't catch the eye because its color is too similar to the background. Furthermore, it looks like the color is the exact same one as the weekend calendar background, resulting in the card not being visible.
Same goes for the switches color: I only know that they're on because the dot is on the right, but it's difficult to see at a glance. On the default theme, for example, they're blue and gray, so you can see instantly which are which.

![](https://i.imgur.com/JSnnYx0.png)
![](https://i.imgur.com/getNZBB.png)
![](https://i.imgur.com/VKIadVP.png)

Would it be possible to bump the contrast of this color a little?

**Comment by dragonwocky** [comment]
I've made some slight changes to improve contrast in the calendar, but the colours are as intended.

**Comment by fabiosangregorio** [comment]
Really looks better with the new changes, thank you.
