### ISSUE TITLE
Visible window area reduced when using "Focus Mode" enhancement

### ISSUE THREAD

**Issue by pranjalshah9814ps** [dragonwocky/notion-enhancer#177]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
When using the "Focus Mode" enhancement, and the sidebar is collapsed (i.e. focus mode is active) there is a blank bar at the bottom of the window which reduces the visible area of the window. This issue does not occur when the "Focus Mode" enhancement is disabled.

**expected behaviour**
Even with the sidebar collapsed, the entire window rea should be visible as it was before collapsing it

**screenshots**
Sidebar Open - Focus Mode Enabled:
![Sidebar Open](https://user-images.githubusercontent.com/62697064/97394962-e60ddb80-1909-11eb-8364-a3e8a447b964.png)
Sidebar Closed - Focus Mode Enabled (Notice the blank bar at the bottom):
![Sidebar Closed](https://user-images.githubusercontent.com/62697064/97395127-3be28380-190a-11eb-98a5-2f2b8cb2faa9.png)

Expected Behaviour when Sidebar Closed:
![Expected](https://user-images.githubusercontent.com/62697064/97395317-b8756200-190a-11eb-8a46-79aebfd611f7.png)

**platform**
Windows 10
Notion Enhancer build 0.10.0-wip

**Comment by dragonwocky** [comment]
This is intentional - focus mode is intended to be used when in full-screen and you want a no-distraction/blank canvas just to write on, and so if you have empty space on 3 sides it makes sense to make that consistent it with a 4th.

I'll add an option to turn it off, though, because it has confused a couple people.

**Comment by pranjalshah9814ps** [comment]
Thanks a lot!
I get where you're coming from but I personally found that to be quite jarring, having the content terminate before the window/screen edge.
I was having some trouble updating it but after I did it works wonderfully!
