### ISSUE TITLE
Autocorrection feature

### ISSUE THREAD

**Issue by sarah2935** [dragonwocky/notion-enhancer#178]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**problem**
why do you need this feature? without autocorrection, lowers efficiency, and is a feature every user would love to have. Almost all well-known writing apps eg. Google docs, Pages, Microsoft word have this feature.

**solution**
how do you want this feature to appear/act? do you have any suggestions for how it could be implemented?
automatically correct spelling and/or grammatical issues

**alternatives (optional)**
have you tried to do this yourself? have you seen it done somewhere else?
would a different feature remove the need for this?

**Comment by dragonwocky** [comment]
would be part of #166 if it can be done.
