### ISSUE TITLE
Changes aren't applied to Notion

### ISSUE THREAD

**Issue by nefks** [dragonwocky/notion-enhancer#179]
Hey! I installed the notion enhancer by running the code in WSL and everything seemed to be going fine  with the enhancer automatically popping up when I opened Notion. The problem thought is that when I make a certain change and reopen the Notion app nothings seems to actually change. Is there a fix for that? Am I doing something wrong?

**Comment by dragonwocky** [comment]
How are you making the changes, what changes are they and how are you reopening the Notion app?
The recommended way to be sure something has applied is to click the "relaunch" button at the top of the menu after changing any settings.

Also note if it's themes you're having a problem with (this has been an issue for a few people): dark themes will only work if Notion is in dark mode and light only in light mode. You can toggle this with `ctrl+shift+L` or from in-app settings.

**Comment by nefks** [comment]
I was trying to apply a dark theme while not in dark mode. Thank you so much!
