### ISSUE TITLE
Sync Dark Mode With System Theme (And More?)

### ISSUE THREAD

**Issue by torchatlas** [dragonwocky/notion-enhancer#18]
**problem**
I like using light mode during the day, and dark mode during the night. My system automatically changes for this. I wish Notion did too.

**solution**
My device automatically switches between light and dark mode at the relevant timing. In addition, there is a feature in web browsers nowadays that detects whether the system is on light or dark mode. This could be used for this purpose.

In addition, one can switch between modes with Ctrl+Shift+L. I'm not sure exactly how this feature is going to be implemented, but here's an idea:

Let's say the person has set their system to switch into dark mode at 9PM. It's 9PM, and the system dark mode has changed. The user is not using Notion at the time. However, the Python script will watch for when the user starts using the Notion window again. Once the user does, the Python script will emulate the click of Ctrl+Shift+L.

There's probably a better way to do this, though. Like, injecting a different CSS theme when system theme changes. Of course, there will be a warning before Notion restarts.

**note**
This feature suggestion is why I suggested a [custom Settings GUI](https://github.com/dragonwocky/notion-enhancer/issues/17), because a feature like this can get too complex for a tray icon.

**Comment by dragonwocky** [comment]
👍🏽 will make this one of the modules available as part of #6/#7

**implementation**
- option to toggle between using system colour theme or manual colour scheme
if selected, theme will be chosen based on current system preference (light/dark). `CTRL+SHIFT+L` will not do anything.
if unselected, behaviour will return to normal (theme toggled by shortcut).

**Comment by dragonwocky** [comment]
at the moment the only way i've found to manually trigger a theme change is via
```js
localStorage.theme = JSON.stringify({mode:"dark" == JSON.parse(localStorage.theme).mode ? "light" : "dark"}); location.reload()
```

**Comment by dragonwocky** [comment]
https://github.com/dragonwocky/notion-enhancer/commit/330e5a5f6200895f34edcc3528d6049b90762548
