### ISSUE TITLE
Global Default to Show/Hide DB Properties for "Property Layout" Enhancement

### ISSUE THREAD

**Issue by pranjalshah9814ps** [dragonwocky/notion-enhancer#180]
**problem**
When the "Property Layout" enhancement is enabled, the properties of database entries are collapsed/hidden by default. These properties are an integral part of the database entry. Hence, while the user may want to collapse/hide them, they may not want these properties to be hidden by default.

**solution**
Have a global toggle/list option to allow the user to choose whether to have the properties collapsed/hidden or expanded/visible by default. This would be a global default with the option available when the "Property Layout" enhancement has been enabled.

**notes**
I understand that this issue is a partial duplicate of #144 which has been closed and merged into #159. However I have chosen to open this as a new issue since #159 deals primarily with per-database customisation and I believe a global option would benefit users as well and might be more easily implementable until #159 is implemented in its entirety.

**Comment by dragonwocky** [comment]
A global is already part of the suggested implementation in #159. None of it would be particularly difficult to implement, I might as well just add full functionality, I've just been focusing on other things for this release that have been difficult and time-consuming.
