### ISSUE TITLE
Reduce min-width in table columns

### ISSUE THREAD

**Issue by fabiosangregorio** [dragonwocky/notion-enhancer#181]
**problem**
I have some tables with checkboxes and I'd like to reduce the columns width to match the width of the checkbox. As an example look at this habits table: column names are week days, but on a small screen (Surface pro) I can't see all columns because of the default min width of the columns. I would like to replace the column names from "Monday", "Tuesday",... to "MO", "TU" etc. and shrink the column widths to the checkbox width to avoid unnecessary blank space.

![](https://i.imgur.com/A5UnuDa.png)

**solution**
I would love to be able to shrink the width of the columns past the current min-width limit imposed by notion.

Do you think this could be worth the effort?

**Comment by dragonwocky** [comment]
Have you tried https://github.com/dragonwocky/notion-enhancer/blob/master/TWEAKS.md#table-columns-below-100px?

**Comment by fabiosangregorio** [comment]
@dragonwocky no sorry I actually didn't try it. But that tweak is on a per-column, per-table basis, right?

I assume this can't be done/it's difficult to to this globally?

**Comment by dragonwocky** [comment]
Yeah, can't be done.

**Comment by chavlji** [comment]
+1

**Comment by agnisadienis** [comment]
Why is this closed? Also, I tried to open the link for the solution, but it seems it is no more active. I have the same question. I could have an emoji in the column name place and property would be checkBox. Why is this not being considered, more over implemented?

**Comment by dragonwocky** [comment]
@agnisadienis this was closed because the enhancer doesn't have any control over the part of notion's source code that restricts this. There is no way for table columns to be dynamically resized below 100px.

An individual column can be manually resized with CSS as per https://github.com/notion-enhancer/tweaks/blob/main/tweaks/table%20columns%20below%20100px.md (updated version of previous link).

**Comment by agnisadienis** [comment]
@dragonwocky Thank you very much for the given input. If I may say then I think you should think of a way, how to implement in default-notion, but anyways Thank you for the link. I hope that this time it is going to be kept alive. Also: make the notion even better. I believe we can make it even more awesome and the community is undoubtedly asking for many cool things to be added.
