### ISSUE TITLE
Disable UI animations

### ISSUE THREAD

**Issue by sakaa** [dragonwocky/notion-enhancer#182]
Disable UI animations

**problem**
The UI animations take up valuable time when navigating around the interface. What I love about notion is that you can navigate entirely from the keyboard, going up and down, focusing different blocks, change pages and search. It's all really lovely. I just wish I could disable the animations entirely.

**solution**
I wish there was simply a toggle setting to disable all UI animations.

**alternatives (optional)**
I have tried to go through the browser and override the CSS but I can't figure out how to do it. There's seems to be some javascript which blocks my attempts.

---------------
I just want to say thank you very much for putting all this together and hopefully you can see the merit of what I'm suggesting. Thanks again!

Cheers
Sacha

**Comment by dragonwocky** [comment]
![image](https://user-images.githubusercontent.com/16874139/97761612-3da28600-1b5a-11eb-9d5d-18b795c2f98e.png)
Already exists, will be out soon.

**Comment by sakaa** [comment]
Alright! Awesome! Thank you for the response!

**Comment by sakaa** [comment]
Hey thank you for this feature! I just successfully installed the
enhancements! It's so great! Thanks again for making this!

I was wondering though if there's a way to completely disable the
animations, not just make them faster?

Cheers
Sacha

**Comment by dragonwocky** [comment]
@sakaa the "snappy transitions" sets the animation time for all animations to 0s, aka them not being animated at all. have you found otherwise?

**Comment by sakaa** [comment]
Hello, thank you for the quick response!

Yes? Maybe I'm doing something wrong. I have snappy transitions on, I
relaunch Notion, however, things are still animating?

Cheers
Sacha

**Comment by dragonwocky** [comment]
oh, sorry, yeah. all CSS animations (e.g. on hover) are made instant by snappy transitions, but since things like the sidebar sliding in and out are managed by changing the width pixel-by-pixel with javascript, they can't be blocked.

**Comment by Sachawech** [comment]
ah damn, I specifically wanted to remove the animation when selecting
blocks. You know when they go blue?

**Comment by dragonwocky** [comment]
as in, you don't want them to go blue? cos just testing now I can't notice any transition/animation I need to wait for, it seems pretty instant (using `shift+arrows` to select.)

**Comment by Sachawech** [comment]
No no I definitely want them to turn blue so I can see that they're
selected, it's just that it's not instant. There's a tiny fade animation.
I'd like to remove this so selecting blocks is completely instant.

I'm also using shit+arrows to select. You don't see the animation?

**Comment by dragonwocky** [comment]
I see it, but it only seems to take ~100ms. It's just not as if it's something I need to wait for (or even something I would've noticed if you hadn't pointed it out)...

This CSS should disable that anyway, I'll include it in the next release:
```css
.notion-selectable-halo {
  opacity: 1 !important;
}
```

**Comment by Sachawech** [comment]
Awesome! Thank you so much! I definitely notice hehe. I tried talking to
the developers of Notion but they wouldn't help me. While the other
features you offer in the enhancements are all great, getting rid of this
animation is the main reason I'm trying to customize Notion. I want to go
fast! hehe

Thanks again!

Cheers
Sacha
