### ISSUE TITLE
Using "/", the selected "BASIC BLOCKS" cannot be displayed

### ISSUE THREAD

**Issue by EagerD** [dragonwocky/notion-enhancer#187]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
Only the "dracula" plugin was selected.
When using "/", the selected "BASIC BLOCKS" cannot be displayed or seen. This problem caused me not to know which block to choose.

**expected behaviour**
why is this a bug - what should be happening?
When I press "/", I can see which "BASIC BLOCKS" is selected.

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/44224427/97843305-054ea380-1d24-11eb-8ae9-9556e5f41498.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
windows 10

**Comment by dragonwocky** [comment]
hi @EagerD, does this only happen with the dracula theme or with others too?

**Comment by EagerD** [comment]
Among the plug-ins I have used, "dark+" and "material ocean" also have this problem. This situation may be caused by the "BASIC BLOCKS" color setting in the corresponding plug-in being too dark.



EagerD
 
From: Tom
Date: 2020-11-02 16:33
To: dragonwocky/notion-enhancer
CC: EagerD; Mention
Subject: Re: [dragonwocky/notion-enhancer] Using "/", the selected "BASIC BLOCKS" cannot be displayed (#187)
hi @EagerD, does this only happen with the dracula theme or with others too?

**Comment by runargs** [comment]
This is an issue with `--theme_dark--interactive_hover` not being visible enough. I'm implementing fixes now for dracula and dark+ 👍
