### ISSUE TITLE
Table title bars still dark in light mode

### ISSUE THREAD

**Issue by thehuntresswillow** [dragonwocky/notion-enhancer#19]
Hey, this is u/thehuntresswillow from Reddit. Just submitting a bug report as requested. The title bars for all of my tables still have a dark background in light mode. (Windows 10) This occurred on my first run of Notion Enhancer, at that point I hadn't edited any of the CSS or anything.

Thanks in advance for your help. :)

<img width="461" alt="themecss tableview" src="https://user-images.githubusercontent.com/68186140/87244795-de4c2900-c437-11ea-984c-69cf7f7e30a7.png">

<img width="752" alt="title bar dark" src="https://user-images.githubusercontent.com/68186140/87244796-e015ec80-c437-11ea-87ba-f7a0174a4ce0.png">

<img width="752" alt="title bar light" src="https://user-images.githubusercontent.com/68186140/87244798-e310dd00-c437-11ea-9e3e-4da2f26bcbac.png">

**Comment by dragonwocky** [comment]
reopened, personally solved != bug fixed

**Comment by dragonwocky** [comment]
fixed in 5752a95c23254b0bb43594fde3634a81ef7cb5d7
