### ISSUE TITLE
Middle mouse button click to open in new tab

### ISSUE THREAD

**Issue by raphapotens** [dragonwocky/notion-enhancer#194]
Like we can do in any browser, 
I always use this way to open links or close tabs (close tabs already a feature on notion-enhancer with middle click, thanks!)

0.10.0 Awesome update! Thanks godly @dragonwocky to make our life easier and awesome with notion!

**Comment by dragonwocky** [comment]
While testing stuff for middle clicking links I discovered it actually does serve a purpose, albeit a small one: middle clicking will bypass preview and go straight into a page. It might cause some odd behaviour if I try to override current click handlers (that are handled by obfuscated Notion code I can't read), so I'm leaving that as is.
