### ISSUE TITLE
Unable to find Electron App

### ISSUE THREAD

**Issue by balajsra** [dragonwocky/notion-enhancer#20]
**describe the bug**
Followed installation instructions to install dependencies, download enhancer (locally cloned repo), ensured no processes are running, ran `cleaner.py`, then ran `customiser.py`.
After this, ran `notion-app` and got the following error message:
```
Error launching app
Unable to find Electron app at /opt/notion-app/app.asar

Cannot find module '/opt/notion-app/app.asar'
Require stack:
- /usr/lib/electron6/resources/default_app.asar/main.js
-
```
This appears to be the same error mentioned in [this comment](https://github.com/dragonwocky/notion-enhancer/pull/4#issuecomment-649998217) from #4.

Also attempted to run enhancer using [released zip](https://github.com/dragonwocky/notion-enhancer/archive/master.zip#), same issue.

**expected behaviour**
Expected notion to launch with the default notion-enhancer styling.

**screenshots**
Left side shows the logs from running `cleaner.py` and `customiser.py`.
Right side shows the error message from attempting to open `notion-app` as well as the contents of the `/opt/notion-app/` directory where the error message says it is unable to find `/opt/notion-app/app.asar`.
![Screenshot_20200712_144626](https://user-images.githubusercontent.com/22876640/87254173-a2708e00-c44e-11ea-8691-2c6ef773cdfe.png)

**platform**
OS: Arch Linux 64-bit
Notion App: notion-app 1:2.0.7-3 from [AUR](https://aur.archlinux.org/packages/notion-app/)

**Comment by dragonwocky** [comment]
what's the contents of `/usr/bin/notion-app` and `/opt/notion-app/notion-app`?
if you go into `/opt/notion-app/notion-app` and replace `electron app.asar` with `electron app`, does that fix it?

**Comment by balajsra** [comment]
# Original File Contents

## /usr/bin/notion-app
```
#!/usr/bin/env bash
#
# Launch notion.so

if [[ ! -e "/opt/notion-app" ]]; then
  echo "Error: /opt/notion not found"
  exit 1
fi

pushd "/opt/notion-app/" >/dev/null || exit 1
electron6 app.asar
popd >/dev/null || exit 1
```

## /opt/notion-app/notion-app
```
#!/usr/bin/env bash
#
# Launch notion.so

if [[ ! -e "/opt/notion-app" ]]; then
  echo "Error: /opt/notion not found"
  exit 1
fi

pushd "/opt/notion-app/" >/dev/null || exit 1
electron6 app.asar
popd >/dev/null || exit 1
```

# Solution
As you suggested, replacing `electron app.asar` with `electron app` in `/opt/notion-app/notion-app` solved the problem.

## /opt/notion-app/notion-app
```
#!/usr/bin/env bash
#
# Launch notion.so

if [[ ! -e "/opt/notion-app" ]]; then
  echo "Error: /opt/notion not found"
  exit 1
fi

pushd "/opt/notion-app/" >/dev/null || exit 1
electron6 app
popd >/dev/null || exit 1
```
