### ISSUE TITLE
Tray Options Not Working

### ISSUE THREAD

**Issue by balajsra** [dragonwocky/notion-enhancer#21]
**describe the bug**
When any of the tray options are enabled, the expected behavior does not occur.

**expected behaviour**
For example, I tried enabling the tray option to `Load theme.css` and reloading the app, but the theme does not change.

**screenshots**
Before enabling theme tray option, notion app is using default dark theme.
![Screenshot_20200712_184053](https://user-images.githubusercontent.com/22876640/87258134-5a159800-c46f-11ea-9e0c-340a91cfdca3.png)

After enabling theme tray option and reloading, notion app is still using default dark theme.
![Screenshot_20200712_184128](https://user-images.githubusercontent.com/22876640/87258135-5aae2e80-c46f-11ea-91e9-d1d840e3e923.png)

**platform**
OS: Arch Linux 64-bit
Notion App: notion-app 1:2.0.7-3 from [AUR](https://aur.archlinux.org/packages/notion-app/)
DE: KDE Plasma

**Comment by dragonwocky** [comment]
do any of the others work? if you do `CTRL+SHIFT+I` to open the devtools and go the console, are any errors shown?

**Comment by balajsra** [comment]
As far as I can tell, none of the options work. I tried `close to tray`, reloaded, then closed notion and the tray icon disappeared as well.

Here is the log from the devtools console after enabling `Load theme.css`
[www.notion.so-1594600245069.log](https://github.com/dragonwocky/notion-enhancer/files/4909986/www.notion.so-1594600245069.log)

Let me know if I can provide any other information to help debug.

**Comment by dragonwocky** [comment]
if you go to `/opt/notion-app/app/` is there a `user-preferences.json` file? what are its contents? if you change the tray options, do the file contents change?

**Comment by balajsra** [comment]
Here are the contents of /opt/notion-app/app/
```
./   config.js      config.json           helpers/   icon.ico  node_modules/  renderer/  store.js
../  config.js.map  ENHANCER_VERSION.txt  icon.icns  main/     package.json   shared/
```

There is not a `user-preferences.json` file.

**Comment by dragonwocky** [comment]
so I'm guessing that when you close/reopen the app the checked boxes all reset to being unchecked?

what happens if you create a `user-preferences.json` file with the contents set to
```json
{"openhidden":true,"maximized":true,"tray":true,"theme":true,"emoji":true}
```
and then restart the app?

**Comment by balajsra** [comment]
> so I'm guessing that when you close/reopen the app the checked boxes all reset to being unchecked?

Yes, that's correct.

> what happens if you create a user-preferences.json file with the contents set to
> {"openhidden":true,"maximized":true,"tray":true,"theme":true,"emoji":true}
> and then restart the app?

This solved the problem, thank you so much for your help!
