### ISSUE TITLE
Notion enhancer downloads yet does not run proplerly

### ISSUE THREAD

**Issue by idareeve** [dragonwocky/notion-enhancer#214]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

Notion launcher downloads and runs, yet when notion is opened it does not work properly. The pop-up enhancements menu (triggered by alt + e ) on windows for the enhancer is blank and loads continuously. It seems to have half worked, as the close and minimise buttons have disappeared, yet nothing else. It did briefly work but as soon as I relaunch the app, the scenario above happens.

**expected behaviour**
why is this a bug - what should be happening?

The enhancements menu should work.

**screenshots**
if applicable, add screenshots of your problem.

![image](https://user-images.githubusercontent.com/67383708/98278427-7befd900-1f90-11eb-9045-449a6f4dd079.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

Windows 10

**Comment by archetyped** [comment]
Same happening here.  Enhancements window is just a blank white screen with a loading spinner and window controls for Notion app windows are not displayed.

Strangely, the latest notion-enhancer release (v0.10.0) installed and ran fine initially (tested out new tabs feature, etc.), but it suddenly stopped working despite not making any changes to notion-enhancer between the time that it worked and stopped working.

**platform**

Windows 10/WSL2

**Comment by bsherin** [comment]
Same happening here on macOS Catalina

**Comment by Theguyhere0** [comment]
Can confirm on Windows 10 here as well. I got it to work once when I uninstalled and reinstalled the extension, but it's not a guarantee. Another important note is that the top bar doesn't work either whenever I relaunched Notion through the extension. Whenever the menu is not working, the top bar doesn't work either.

**Comment by bsherin** [comment]
I just tried removing notion-enhancer form the command line. Then I re-applied and now it works (all again on macOS Catalina). Guess I should have tried that before,

**Comment by idareeve** [comment]
> I just tried removing notion-enhancer form the command line. Then I re-applied and now it works (all again on macOS Catalina). Guess I should have tried that before,

Already tried that multiple times and it worked for a bit and then stopped as soon as I closed notion again

**Comment by archetyped** [comment]
@dragonwocky can you please link to the issue that this issue is a duplicate of so that we can stay up to date with any further updates?

Thanks.

**Comment by dragonwocky** [comment]
#197 - it's already fixed, will be released soon
