### ISSUE TITLE
Notion app isn't opening

### ISSUE THREAD

**Issue by kerningium** [dragonwocky/notion-enhancer#219]
I enabled an extension that allows opening any database as a page (I don't remember exactly). I relaunched the application and, it's not opening anymore.

I tried re-installing both Notion-enhancer and Notion. But, none of them worked. As soon as I install the notion-enhancer again, Notion stops working. 
![image](https://user-images.githubusercontent.com/73218471/98368566-96dc4f00-205d-11eb-9e9e-513931e4b1b6.png)

**Comment by kerningium** [comment]
I'm using Windows 10. One more thing, the Windows button/Title bar button is working even though it is not visible.

**Comment by kerningium** [comment]
I removed the .notion-enhance folder and it fixed the problem. There is one more thing it is showing wrong page icon on tab

**Comment by serjanbiogenic** [comment]
I have exact same issue both on Mac 10.15.7 and Windows 10. Suddenly both stopped working and having this looping loading icon. 
Removing Notion Enhancer made it work. Looking forward to have the bug fixed, missing my fav enhancer features!

**Comment by megclaypool** [comment]
I can install the enhancer and everything works great! But once I restart my computer, when I try to launch Notion I get the message: `The application “Notion” can’t be opened.`

MacOS 10.15.7

**Comment by aarjav24** [comment]
I'm facing the same issue. All I see is the loading icon.
Windows 10

**Comment by ChrisRaveendra** [comment]
I encountered a similar issue of being stuck on the loading icon upon starting the app. On Windows 10.

Although in my case I was able to resolve the issue with a reinstall. I uninstalled the module, then made sure that Notion worked properly with it removed, and then reinstalling Notion Enhancer.

**Comment by kerningium** [comment]
> I can install the enhancer and everything works great! But once I restart my computer, when I try to launch Notion I get the message: `The application “Notion” can’t be opened.`
> 
> MacOS 10.15.7

Try installing notion-enhancer again, I've faced the same issue and it worked out.

**Comment by kerningium** [comment]
> I'm facing the same issue. All I see is the loading icon.
> Windows 10

Remove the `.notion-enhancer` folder C:\user\[username]\Appdata

**Comment by aarjav24** [comment]
> > I'm facing the same issue. All I see is the loading icon.
> > Windows 10
> 
> Remove the `.notion-enhancer` folder from `C:\Users\[username]\` then try

Donig that removed the title bar for me and the notion-enhancer doesn't open either.

**Comment by kerningium** [comment]
> > > I'm facing the same issue. All I see is the loading icon.
> > > Windows 10
> > 
> > Remove the `.notion-enhancer` folder from `C:\Users\[username]\` then try
> 
> Donig that removed the title bar for me and the notion-enhancer doesn't open either. 

Uninstall notion-enhancer using this command `npm i -g remove notion-enhancer` then open notion again.

**Comment by kerningium** [comment]
> > > > I'm facing the same issue. All I see is the loading icon.
> > > > Windows 10
> > > 
> > > Remove the `.notion-enhancer` folder from `C:\Users\[username]\` then try
> > 
> > Donig that removed the title bar for me and the notion-enhancer doesn't open either. 
> 
> Uninstall notion-enhancer using this command `npm i -g remove notion-enhancer` then open notion again.

If don't works then install notion again

**Comment by kerningium** [comment]
> > > > I'm facing the same issue. All I see is the loading icon.
> > > > Windows 10
> > > 
> > > 
> > > Remove the `.notion-enhancer` folder from `C:\Users\[username]\` then try
> > 
> > 
> > Donig that removed the title bar for me and the notion-enhancer doesn't open either.
> 
> Uninstall notion-enhancer using this command `npm i -g remove notion-enhancer` then open notion again.

Your notion must be looking like this if I'm not wrong. Follow this step, and it will fix your problem. Make sure to close all tasks.
![image](https://user-images.githubusercontent.com/73218471/98432301-ff214400-20e2-11eb-9c46-cf5adf802345.png)
![image](https://user-images.githubusercontent.com/73218471/98432305-02b4cb00-20e3-11eb-8200-83f9822ee68b.png)

**Comment by aarjav24** [comment]
> > > > > I'm facing the same issue. All I see is the loading icon.
> > > > > Windows 10
> > > > 
> > > > 
> > > > Remove the `.notion-enhancer` folder from `C:\Users\[username]\` then try
> > > 
> > > 
> > > Donig that removed the title bar for me and the notion-enhancer doesn't open either.
> > 
> > 
> > Uninstall notion-enhancer using this command `npm i -g remove notion-enhancer` then open notion again.
> 
> If don't works then install notion again

Yes I had to reinstall everything. Notion Enhancer isn't working at all. Will have to live without it until a major bug fix is out. :(

**Comment by aarjav24** [comment]
Upon examining the enhancer, I realised the problem lies in the new tabs feature. All of the issues I opened regarding malfunction of Notion keyboard shortcuts were also caused by this new tabs feature. Upon disabling it, everything seems to be working as intended, although I really need the tabs feature.

**Comment by alessandrobelli** [comment]
> > I'm facing the same issue. All I see is the loading icon.
> > Windows 10
> 
> Remove the `.notion-enhancer` folder from `C:\Users\[username]\` then try

On windows 10 didn't work until I removed this folder...

**Comment by aarjav24** [comment]
Again it has stopped working for me. The titlebar doesn't show up and the enhancer isn't opening. This happened abruptly. Upon deleting the .notion-enhancer folder and uninstalling the enhancer altogether worked for me. I guess it's really buggy and needs some serious patches. Until then, I'll have to stop using this program. Please fix this bug ASAP @dragonwocky.

**Comment by kerningium** [comment]
> Again it has stopped working for me. The titlebar doesn't show up and the enhancer isn't opening. The app, however, does load. This happened abruptly. Upon deleting the .notion-enhancer folder and uninstalling the enhancer altogether worked for me. I guess it's buggy and needs some serious patches. Until then, I'll have to stop using this program. Please fix this bug ASAP @dragonwocky.

Exactly, it happened with me also around 2 or 3 times. Every time the title bar disappears or notion app doesn't launch, I've to install module and notion again.

**Comment by kerningium** [comment]
> Upon using the enhancer and changing some settings, I realised the problem lies in the new tabs feature. All of the issues I opened regarding malfunction of Notion keyboard shortcuts were also caused by this new tabs feature. Upon disabling it, everything seems to be working as intended, although I really need the tabs feature.

I don't think so, as I only use the Dracula theme. But still, I'm facing the same issue.

**Comment by aarjav24** [comment]
> > Upon using the enhancer and changing some settings, I realised the problem lies in the new tabs feature. All of the issues I opened regarding malfunction of Notion keyboard shortcuts were also caused by this new tabs feature. Upon disabling it, everything seems to be working as intended, although I really need the tabs feature.
> 
> I don't think so, as I only use the Dracula theme. But still, I'm facing the same issue.


Yes that's why I mentioned this (PFB) once again. It's not a problem specific to any feature it seems. The program abruptly seems to be causing issues. Needs some real fixes!

> Again it has stopped working for me. The titlebar doesn't show up and the enhancer isn't opening. The app, however, does load. This happened abruptly. Upon deleting the .notion-enhancer folder and uninstalling the enhancer altogether worked for me. I guess it's really buggy and needs some serious patches. Until then, I'll have to stop using this program. Please fix this bug ASAP @dragonwocky.

**Comment by kerningium** [comment]
I don't if anyone has noticed, that even after uninstalling notion-enhancer it is still there. I mean I'm still able to use extensions. 

`npm I -g remove notion-enhancer` I passed this command several times still nothing changes. I'm not able to uninstall the module

**Comment by aarjav24** [comment]
> I don't if anyone has noticed, that even after uninstalling notion-enhancer it is still there. I mean I'm still able to use extensions.
> 
> `npm I -g remove notion-enhancer` I passed this command several times still nothing changes. I'm not able to uninstall the module.

Yes this happened with me as well. What I did was delete the mods folder located here:
C:\Users\(User)\AppData\Roaming\npm\node_modules\notion-enhancer\mods
Hope that solved your problem.

**Comment by dragonwocky** [comment]
@kerningium that's not the right command to uninstall the enhancer: `npm i` will always install, `npm remove` will uninstall. `-g` is the option for a global install rather than just within the folder. try `npm remove -g notion-enhancer`

I am working on this bug but have been busy with a bunch of other stuff for a few days

**Comment by lucasmaffazioli** [comment]
I too experienced problem as soon as I activated tabs, let 2 of them opened and shut down my computer. The next morning it didn't load.

**Comment by Gbillington1** [comment]
This problem is not fixed. I just had to reinstall the notion because the enhancer wouldn't open the app. Whenever I tried to open notion, the enhancer icon would show up on the bottom right of the taskbar, and Notion would not open. When I clicked the icon, nothing happened, when I right-clicked the icon, nothing happened. I tried all of the solutions in this thread, and the only thing that got my regular notion back was uninstalling it and reinstalling it. I am going to try to install the enhancer again, hopefully, it goes well. I will avoid the tabs enhancements and only stick to the themes.

**Comment by Gbillington1** [comment]
Fixed the issue thanks to this: https://github.com/notion-enhancer/notion-enhancer/issues/437#issuecomment-787436709

**Comment by JackVish** [comment]
I had same problem for Mac.. Reset app & clearing local data helps..

**Comment by korry05** [comment]
I have the forever refreshing issue. Not from enhance. I did a notion reset. links: [https://www.notion.so/Reset-Notion-1b70196f1f6145d7a8695afc425d8699](url).
hope this helps.
