### ISSUE TITLE
Copy an event multiple times without the "copy of" prefix

### ISSUE THREAD

**Issue by dopewind** [dragonwocky/notion-enhancer#225]
**Problem**

Every time I copy an event (I alt+drag usually) the newly created event shows up with a "copy of" prefix which is really annoying to remove from each entry

**Solution**

Perhaps an option to disable or modify the prefix text

**Comment by dragonwocky** [comment]
the enhancer doesn't interfere with any notion content/data, it just changes how things look and adds extra app-like functionality.
