### ISSUE TITLE
Notion Not Loading

### ISSUE THREAD

**Issue by KeerthiNaathan** [dragonwocky/notion-enhancer#227]
**describe the bug**
what is the bug - When i use Notion with Notion-Enhancer, The Screen is Loading and Loading and Not Letting me in 

**expected behaviour**
why is this a bug - this is second time, Last time i uninstall and re-install notion and notion-enhancer to solve it. i think due to tab update i think there may be a problem,

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/55060041/98448048-6c6abe80-214f-11eb-9e88-e2b7acdd0b80.png)
The Screen For Past 10-20 Mins

**platform**
what OS are you using? Windows 10 2004

**Comment by ClaireBookworm** [comment]
This is actually happening to me too -- I just reinstalled notion and notion-enhancer a few times and it's still not working (notion is loading now, but the enhancement window is loading forever...) I'm on a mac!

**Comment by KeerthiNaathan** [comment]
@ClaireBookworm For now Just Uninstall Notion and Notion-Enhance and Reinstall it, it will solve the problem as of now. Until the bug is fixed this is our only option.

**Comment by ClaireBookworm** [comment]
Yeah, that worked for me but I had to uninstall it a few times haha

**Comment by aarjav24** [comment]
The same issue has been brought up [here](https://github.com/dragonwocky/notion-enhancer/issues/219), so it's not only you. This program has some inherent issues that need serious fixes. Cannot consider installing it again until there's a new release. :(

**Comment by KeerthiNaathan** [comment]
Yea, I Agreed i did not see it, Thanks for the Notice, I think due to tabs update notion thinks it running in separate browser or something like that. because of that error keeping happening. 
As of Now 2 ways are present.
1.  Uninstall and Reinstall of Notion and Notion-enhancer
2. Deleting .notion-enhancer folder

Sadly, I think there are No Other Option

**Comment by kerningium** [comment]
> Yea, I Agreed i did not see it, Thanks for the Notice, I think due to tabs update notion thinks it running in separate browser or something like that. because of that error keeping happening. 
> As of Now 2 ways are present.
> 1.  Uninstall and Reinstall of Notion and Notion-enhancer
> 2. Deleting .notion-enhancer folder
> 
> Sadly, I think there are No Other Option

The problem is sometimes the title bar disappears after removing the `.notion-enhancer` folder. And it became like a routine for me every time before opening notion after a system reboot uninstall the module.

**Comment by dragonwocky** [comment]
The best current workaround is to:
1. Open notion in your browser
2. Create a new page
3. Click on the 3 dots on the top right and click "Open in Windows app"

This does not require deleting of folders or reinstalling.
