### ISSUE TITLE
Minimalism

### ISSUE THREAD

**Issue by jpaulabbott** [dragonwocky/notion-enhancer#233]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**problem**
Not really a problem, but more of a preference; on Windows there is the ability to "hide" the Notion-Enhancer icon/launcher inside the tool bar menu, on MacOS there's unfortunately no such opportunity.

**solution**
I'm no programmer, but sure there is a way to hide the menu toolbar launcher as a preferential option that exists in many other programs.

**alternatives (optional)**
None known.

**Comment by dragonwocky** [comment]
@jpaulabbott it is possible to hide the icon, but that breaks functionality. Especially at the moment when some of the hotkeys are unreliable, the toolbar menu is necessary to access the enhancer settings.
