### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by timothybones** [dragonwocky/notion-enhancer#235]
**describe the bug**
Notion never loads, it stays in the initial loading screen forever with the loading gif

**expected behaviour**
Notion should load

**screenshots**
This is the screen it's stuck on
![Notion Enhancer broken](https://user-images.githubusercontent.com/3060230/98485678-30794b80-226c-11eb-86fb-1fd14144b733.png)

**platform**
Windows 10 Pro v2004

**Comment by larizzatg** [comment]
I don't know the root of this, but the first time I install the extension it also happened to me. I fixed removing notion enhancer, restarting my pc, enabling notion enhancer, and then starting notion.

**Comment by timothybones** [comment]
Ok.
Thanks for the tip.
Good luck finding and fixing up (I know that pain!)

**Comment by CapedCrusader2** [comment]
I am having the same issue. I have tried restarting my computer, uninstalling Notion Enhancer, uninstalling Notion all with no luck.

**Comment by lucasmaffazioli** [comment]
This also happened to me out of nowhere, yesterday everything was fine, today is stuck.

Notion version 2.9.23.3.40, Desktop 2.0.9, Updated 2 days ago

**Comment by CloudHill** [comment]
There are two workarounds so far to this problem, either by right clicking the enhancer's tray icon and clicking Relaunch, or by using Ctrl + Shit + N on the bugged window to create a new (and hopefully unbugged) window

**Comment by lucasmaffazioli** [comment]
Well, after reinstalling enhancer a few times, the problem was fixed! Don't know exactly what I did it, but is now working.

**Comment by rintran720** [comment]
I opened Cloudflare warp (1.1.1.1), turn on it, and open Notion with fixed

**Comment by MrJemmy** [comment]
I am also facing same issue and also i am in linux
please fix it

**Comment by acerspyro** [comment]
Please take a look at https://github.com/notion-enhancer/notion-repackaged/issues/116

If you're on Linux, in that thread, I provided an easy patcher script. Otherwise, you can manually patch it, or monkeypatch it with the instructions provided in the same thread.
