### ISSUE TITLE
Enhancements window keeps loading

### ISSUE THREAD

**Issue by itsyagirlnina** [dragonwocky/notion-enhancer#237]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
Whenever I click Enhancements, the small window starts loading but it keeps on loading forever. It used to work just fine until I updated the enhancer to the latest version.

**expected behaviour**
why is this a bug - what should be happening?
The window with the possible enhancements should open.

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/66064483/98535946-3af50e80-2287-11eb-814e-4aa7d848883d.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
Windows 10

**Comment by snihar2** [comment]
had the same problem. It was fixed following comment issue #235, you just need to click on relaunch notion, and after two times, it was fixed for me.
