### ISSUE TITLE
Notion-enhancer is Stuck on Loading

### ISSUE THREAD

**Issue by OrelBenny** [dragonwocky/notion-enhancer#251]
Thank you so much for such a great invention. Enhancing indeed! :)

**describe the bug**
I updated the enhancer a few minutes ago and it seems to stop working, even after a restart. 
Tried to reinstall, but there's no change.

**expected behaviour**
I should be able to access the various options. 

**screenshots**
![2020-11-12 15_15_25-Window](https://user-images.githubusercontent.com/74361304/98944692-1785ca00-24fa-11eb-894d-c93148c00bfc.png)

**platform**
windows 10

**Comment by OrelBenny** [comment]
kind of solved the issue. 
I uninstalled the enhancer using `npm remove -g notion-enhancer` in node.js command prompt.
then "power" uninstalled notion via IObit Uninstaller (free edition), and then reinstalled them after a restart.

**Comment by dragonwocky** [comment]
duplicate of https://github.com/dragonwocky/notion-enhancer/issues/197

release will be fixed soon, best workaround at the moment is:
1. Open notion in your browser
2. Create a new page
3. Click on the 3 dots on the top right and click "Open in Windows app"
