### ISSUE TITLE
Notion windows app title bar placed below

### ISSUE THREAD

**Issue by maheshthedev** [dragonwocky/notion-enhancer#26]
**describe the bug**
what is the bug - In windows Notion app title bar (minimize,maximize,close buttons) are placed below

**screenshots**
![image](https://user-images.githubusercontent.com/38828053/88037981-3c2cef00-cb63-11ea-981a-7ceae964dbdc.png)

**platform**
Windows 10

**Comment by dragonwocky** [comment]
Below... what exactly?

That darker line up the top? That's the draggable area. In your screenshot, buttons are placed as intended.
