### ISSUE TITLE
White border line appears on second monitor when Notion window is maximized

### ISSUE THREAD

**Issue by svpaz7** [dragonwocky/notion-enhancer#27]
**Bug description**
When I maximize the window of Notion with this enhancer, there is a white line on the leftmost side of my second monitor (which is positioned to the right of my main monitor). It seems that the program, when maximized, is one pixel wider than my main monitor, and therefore extends to my second monitor, showing a white line that is a pixel wide, and as tall as the height of my second monitor.

It may not seem like it's too distracting, but it would help make Notion with this enhancer look cleaner.

**Expected behavior**
The white line is not supposed to be seen.

**Screenshots**
You can see on the very right side of the following screenshot that there is a white line. My first monitor covers the very left side of the following screenshot, all the way until right before the white line. Anything to the right of the white line, _including_ the white line is my second monitor (I didn't screenshot the whole area of my second monitor as it is not important).
![image](https://user-images.githubusercontent.com/65367607/88203774-e8aec400-cc7c-11ea-9104-fa6ae8b46152.png)

**Platform**
Windows 10 ver 2004

**Comment by dragonwocky** [comment]
if you replace [line 142 of customiser.py](https://github.com/dragonwocky/notion-enhancer/blob/master/customiser.py#L142) with
```
                    '{ show: false', '{ frame: false, show: false, transparent: true')
```
then re-enhancer (run the cleaner script then the customiser script), does that help?

**Comment by svpaz7** [comment]
> if you replace [line 142 of customiser.py](https://github.com/dragonwocky/notion-enhancer/blob/master/customiser.py#L142) with
> 
> ```
>                     '{ show: false', '{ frame: false, show: false, transparent: true')
> ```
> 
> then re-enhance (run the cleaner script then the customiser script), does that help?

Sorry for the late reply. This works, but it removes the ability to drag the window to the topmost of my screen to maximize the window, or to the left/right for split-screen view.

**Comment by dragonwocky** [comment]
Alright. I haven't been able to duplicate this recently in my WIP build, so I may have accidentally fixed it already. That should be out in about a week... when it's released, see how that goes.
If you'd like to beta-test it sooner, message me on Discord `dragonwocky#8449`

**Comment by dragonwocky** [comment]
is this still present in v0.8.0?

**Comment by dragonwocky** [comment]
yeah, i can't replicate it anymore with my screen- i'm going to assume this is fixed and close it for now unless reported otherwise
