### ISSUE TITLE
Can't found app.asar when installing

### ISSUE THREAD

**Issue by pengzhenghao** [dragonwocky/notion-enhancer#28]
**describe the bug**
what is the bug - what happens?

Error happens.
```
=== NOTION ENHANCER CUSTOMISATION LOG ===

 ## file /Applications/Notion.app/Contents/Resources/app.asar not found!
 * attempting to locate
 > nothing found: exiting. notion install is either corrupted or non-existent.
```
**expected behaviour**
why is this a bug - what should be happening?

**screenshots**
if applicable, add screenshots of your problem.

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS

macOS Mojave

The fils in the resources folders are:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/22206995/88269603-e8f3a180-cd06-11ea-847a-617aa23b94d3.png">

**Comment by dragonwocky** [comment]
if you rename `app.asar.bak` to `app.asar` and then try running, does that help?

**Comment by pengzhenghao** [comment]
Well, thanks for your reply! I run `python cleaner.py` then run the installation script and it works! Thanks for your effort~
