### ISSUE TITLE
Running customiser.py without install asar leaves Notion in a bad state

### ISSUE THREAD

**Issue by jgscherber** [dragonwocky/notion-enhancer#29]
**describe the bug**
I know this isn't following the install instructions, but still not an ideal situation

I ran `python customise.py` prior to having `asar` install, so as expected, it failed. It also renamed my `asar.app` to `asar.app.bak`, leaving Notion unable to start

This is the failure I got on the intial run

```
=== NOTION ENHANCER CUSTOMISATION LOG ===

 ...unpacking app.asar
'asar' is not recognized as an internal or external command,
operable program or batch file.
 ...renaming asar.app to asar.app.bak

### ERROR (report this to dragonwocky#8449 on discord) ###
[Errno 2] No such file or directory: 'C:\\Users\\JSCHERBER\\AppData\\Local\\Programs\\Notion\\resources\\app\\ENHANCER_VERSION.txt'

=== END OF LOG ===
```

**expected behaviour**
If the script fails due to `asar` not existing, it shouldn't continue, and continue to rename the file

**platform**
Windows 10

**Comment by dragonwocky** [comment]
customisation script already fixed in the wip branch.
any changes (good or bad, including the rename to `asar.app.bak`) made to the app can be fixed by running `cleaner.py`, which is made reasonably clear in the README:
> 7. optional: to remove previous applications of the notion enhancer, run `cleaner.py`.

**Comment by jgscherber** [comment]
sorry - didn't see your comment before making the pull request
