### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Rezuk4** [dragonwocky/notion-enhancer#33]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
1st time install
At step:    python customiser.py,   
 cmd prompt says: 
  File "customiser.py", line 63
    print(f' ## file {os.path.join(filepath, "app.asar")} not found!')
                                                                    ^
SyntaxError: invalid syntax

**expected behaviour**
because of this, enhancer is not working  :(

**screenshots**
![image](https://user-images.githubusercontent.com/69235512/89382000-508ff080-d6fa-11ea-85df-55aa4153eada.png)

**platform**
windows 10

**Comment by dragonwocky** [comment]
which version of python are you using?

**Comment by Rezuk4** [comment]
Hi :)
I've' installed:   python-3.8.5-amd64.exe
<https://www.python.org/ftp/python/3.8.5/python-3.8.5-amd64.exe>

**Comment by Rezuk4** [comment]
I used the lastest:    Python 3.8.5  from  www.python.org

Reading your answer:
I uninstalled 3.8.5,    installed the one from Microsoft Store,  reboot.
Still the same syntax error  :'(

**Comment by dragonwocky** [comment]
odd... this is already fixed in the wip update, but only because it's written entirely without python.
don't think there's a simple fix, then, sorry. you might just have to wait a few days :/

**Comment by Rezuk4** [comment]
I'm OK the waiting ^^
Anyway, thanks for support (and the work) ;)

**Comment by rosiecube** [comment]
It probably ran with Python 2.7.
Check the path. :)

**Comment by Rezuk4** [comment]
You were right,  it was running with another ActivePython 2.7  instead of
the newly installed 3.8...
how did you find that ?! :D
Anyway, Great support ! :o

Thank You

**Comment by chcgnzls** [comment]
I've run into a similar problem but I'm using 3.5.4

```{python}
Python 3.5.4 (v3.5.4:3f56838976, Aug  7 2017, 12:56:33) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from notion.client import NotionClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/checo/pyenv/notion/lib/python3.5/site-packages/notion/client.py", line 103
    raise Exception(f"Not Found {email}, Available IDs: {list(email_uid_dict)}")
                                                                              ^
SyntaxError: invalid syntax
>>> 
```
