### ISSUE TITLE
Updating theme.css does not change appearance

### ISSUE THREAD

**Issue by HarrisonFretwell** [dragonwocky/notion-enhancer#36]
Changing the theme.css file does not have any noticeable change in the appearance of the app. Changing user.css works just fine though.

I've tried making a variety of changes, none of which have any impact. This also includes reinstalling notion, using the cleaner.py file and using a fresh copy of notion-enhancer.

In particular I'm aiming to change the background colour, such as --theme-main etc. I've tried changing them to obvious colours such as rgb(0,255,0), which has no effect. The background colour remains unchanged even on a fresh copy of notion-enhancer, with only the theme-main changed to bright green.
This is on windows 10.

**Comment by dragonwocky** [comment]
@HarrisonFretwell have you enabled it in the tray menu?

**Comment by HarrisonFretwell** [comment]
Ah sorry must have missed that! For anyone else who missed it like I did, you just have to enable theme.css in the tray menu at the bottom right of the screen.
