### ISSUE TITLE
No such file or directory: 'asar'

### ISSUE THREAD

**Issue by greenbicycle** [dragonwocky/notion-enhancer#37]
**describe the bug**
what is the bug - what happens?
When I try to run customiser.py, I get an error. See below:
```
# python3 customiser.py
=== NOTION ENHANCER CUSTOMISATION LOG ===

 ...unpacking app.asar

### ERROR (report this to dragonwocky#8449 on discord) ###
[Errno 2] No such file or directory: 'asar'

=== END OF LOG ===
```
I have installed asar and can run it from the command line.

**expected behaviour**
why is this a bug - what should be happening?
The script should run without error. I haven't run it before. So I am not entirely sure what successful looks like.

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/3146643/89722968-2f066180-d9a5-11ea-806f-56555d9f4ca5.png)

**platform**
I am on an iMac using zsh. OS = 10.5.6.

**Comment by dragonwocky** [comment]
did you install asar? `npm i -g asar`

**Comment by greenbicycle** [comment]
Yes. I can run asar from the command line. But for some reason customiser.py can't find it.

**Comment by greenbicycle** [comment]
This is just an issue with me not having the node binary path in my PATH. To get past this, I just changed the subprocess line to call asar with the full path. That seemed to have worked. I should make sure that .node/bin is in my path. That would probably fix it.
