### ISSUE TITLE
Titlebar doesnt hide

### ISSUE THREAD

**Issue by lx200916** [dragonwocky/notion-enhancer#38]
**describe the bug**
what is the bug - what happens?
Titlebar doesnt hide when customized titlebar shows.Seems like content in `createWindow.js` changed from 
```
{ show: false
```
to
```
({
        ...rect,
        show: false, 
```
in some version of Notion Desktop Windows Platform.
**expected behaviour**
why is this a bug - what should be happening?
Titlebar hides, window frameless.
**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/44310445/89844506-59773b00-dbae-11ea-9fff-fde6626885f7.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
Windows 10

**Comment by dragonwocky** [comment]
already fixed in the next update, which is only a few days from being ready for use.

**Comment by dragonwocky** [comment]
(reopened until fix is actually released.)

**Comment by rosiecube** [comment]
I got it from the forked repository and solved it.

https://github.com/lx200916/notion-enhancer

**Comment by dragonwocky** [comment]
fix released in v0.8.0
