### ISSUE TITLE
I ran `./customiser.py` and get some errors

### ISSUE THREAD

**Issue by JackQAQ-byte** [dragonwocky/notion-enhancer#40]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
I ran `./customiser.py` and get some errors

**expected behaviour**
the program runs 

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/66677431/90116374-f9d48780-dd87-11ea-96c6-d494546796c6.png)

**platform**
Arch linux

Thanks!

**Comment by dragonwocky** [comment]
it's not a bash script, it's a python file. needs to be run with the `python` command

**Comment by JackQAQ-byte** [comment]
Ohh sorry for that 
Yeah I can run it by `python` command, thanks!
