### ISSUE TITLE
Ran `customiser.py` but seems like scrollbar  haven't changed

### ISSUE THREAD

**Issue by JackQAQ-byte** [dragonwocky/notion-enhancer#41]
I'd run the command, but the scrollbars didn't change
![image](https://user-images.githubusercontent.com/66677431/90153712-e5aa7d80-ddbb-11ea-9644-4adc05645bce.png)

**Comment by dragonwocky** [comment]
It doesn't really look like anything changed... where did you install the app from? What was the output in the terminal after you ran `python customiser.py`?

**Comment by AlieZVzz** [comment]
> It doesn't really look like anything changed... where did you install the app from? What was the output in the terminal after you ran `python customiser.py`?

it happened after i updated the newest version of notion

**Comment by dragonwocky** [comment]
so was it previously working?

**Comment by AlieZVzz** [comment]
> so was it previously working?

absolutely

**Comment by JackQAQ-byte** [comment]
Fixed by changing the change those lines where it says `electron6 app.asar` to `electron6 app` in both `/opt/notion-app/notion-app` and `/usr/bin/notion-app`
@dragonwocky said that it will be fix in the next version (which should be released within a week) so we don't have to manually do it
Issue closed :)
