### ISSUE TITLE
Notion no longer enhanced

### ISSUE THREAD

**Issue by soberoi29** [dragonwocky/notion-enhancer#43]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
couple of days ago, coinciding with the notion update, the enhancer stopped enhancing and notion reverted back to original

**expected behaviour**
enhancer should be working (i.e. better scroll bars are gone, no darker theme, menu at the top is nestled under the orignal)

**screenshots**
![image](https://user-images.githubusercontent.com/64914258/90331879-5ae2a200-dfb8-11ea-9235-d1f0ffed80b1.png)

**platform**
windows 10

**Comment by dragonwocky** [comment]
known, solved by the update (95% done)

**Comment by Stealthinator16** [comment]
how to update notion enhancer when the next version eventually drops?

**Comment by harizgithub** [comment]
> how to update notion enhancer when the next version eventually drops?

just git-clone the repo or download it and install the .py file again

**Comment by dragonwocky** [comment]
> > how to update notion enhancer when the next version eventually drops?
> 
> 
> 
> just git-clone the repo or download it, run cleaner.py, and install the customiser.py file again 

no, the installer no longer uses python. there'll be an informative update guide and installation instructions for the update released tonight.

**Comment by dragonwocky** [comment]
fix released in v0.8.0
