### ISSUE TITLE
PLS HELP ME

### ISSUE THREAD

**Issue by wangwei8828** [dragonwocky/notion-enhancer#45]
Hello,
I installed the notion with scoop. And I'm having problems with notion enhancer. Please see the screenshot below. How do I fix it?

![screenshot](https://user-images.githubusercontent.com/18374666/90521054-a81f6900-e19c-11ea-8f46-dec4b595bf3a.PNG)

**Comment by dragonwocky** [comment]
what's the output of running `python cleaner.py`?

**Comment by wangwei8828** [comment]
> what's the output of running `python cleaner.py`?

![捕获](https://user-images.githubusercontent.com/18374666/90524844-23831980-e1a1-11ea-8036-d5f821933e6d.PNG)

**Comment by wangwei8828** [comment]
The directory path of notion is 
C:\Users\TINY\scoop\apps\notion

**Comment by dragonwocky** [comment]
try installing [official windows app](https://www.notion.so/desktop). the enhancer does not currently support installation with scoop.
