### ISSUE TITLE
Can't install Notion Enhancer

### ISSUE THREAD

**Issue by caiweihan** [dragonwocky/notion-enhancer#46]
I download Notion Enhancer and tried to install it for the first time on Windows, and this error message occurred.
![image](https://user-images.githubusercontent.com/29276271/90726667-a8cb1300-e2f4-11ea-9f01-77bc9f66c775.png)

How can I solve this problem?

**Comment by dragonwocky** [comment]
what is your system language?

**Comment by caiweihan** [comment]
> what is your system language?

Simplified Chinese. My user name is also Chinese.

**Comment by dragonwocky** [comment]
does v0.8.0 work?

**Comment by dragonwocky** [comment]
closing due to lack of response, if this is still an issue please let me know and i'll reopen it.
