### ISSUE TITLE
Notion won't open after customisation --> Following FAQ does not solve problem

### ISSUE THREAD

**Issue by edwardsaunders7** [dragonwocky/notion-enhancer#48]
**describe the bug**
Notion won't open after running customiser.py - have followed advice on running cleaner.py and rebooting, and then re-running customiser.py - issue persists. Notion is not running (checked task manager)

**expected behaviour**
This issue should be resolved by following the FAQ guidance.

**screenshots**
![2020-08-25_21-30_2](https://user-images.githubusercontent.com/51308267/91224703-69e4f500-e71a-11ea-8679-9c4d9817d89e.png)
![2020-08-25_21-30_1](https://user-images.githubusercontent.com/51308267/91224705-6a7d8b80-e71a-11ea-8173-532e23f76958.png)

**platform**
Manjaro Linux 5.7.15-1 -> AUR notion-app version 1:2.0.7-3.2

**Comment by dragonwocky** [comment]
Can you try the fixes from https://github.com/dragonwocky/notion-enhancer/issues/41 / https://github.com/dragonwocky/notion-enhancer/issues/20? The linux installer has some faults that should be fixed in the next update.

**Comment by edwardsaunders7** [comment]
Hi, so sorry. I hadn't see that fix. I will close this report

#41 worked for me
