### ISSUE TITLE
Notion Enhancer is overlapping the normal version

### ISSUE THREAD

**Issue by maheshthedev** [dragonwocky/notion-enhancer#49]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - Last night i found that normal notion header is showing on top, below that notion-enhancer header  

**expected behaviour**
why is this a bug - only Notion-enhancer header should display

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/38828053/91266249-b8cc7200-e78e-11ea-9c3a-7ccadb757d73.png)

**platform**
what OS are you using?
Windows 10

**Comment by dragonwocky** [comment]
dup of #43

**Comment by maheshthedev** [comment]
It **didn't worked** Man. I updated the Enhancer as well.

**Comment by dragonwocky** [comment]
the fix isn't released yet.
