### ISSUE TITLE
How to change?

### ISSUE THREAD

**Issue by maheshthedev** [dragonwocky/notion-enhancer#5]
How can i change the minimize button,maximize button, Close button shapes? I just want to change those three button shapes to other shapes that i had.

**Comment by dragonwocky** [comment]
To change the icons, replace them on lines https://github.com/dragonwocky/notion-enhancer/blob/master/resources/preload.js#L56 + https://github.com/dragonwocky/notion-enhancer/blob/master/resources/preload.js#L60 (always-on-top), https://github.com/dragonwocky/notion-enhancer/blob/master/resources/preload.js#L67 (minimise), https://github.com/dragonwocky/notion-enhancer/blob/master/resources/preload.js#L73 (maximise), and https://github.com/dragonwocky/notion-enhancer/blob/master/resources/preload.js#L89 (close).

**Comment by maheshthedev** [comment]
how do you guys get the text format of this buttons. I had in the png format. or recommend sources that you guys used.

**Comment by dragonwocky** [comment]
@maheshthedev these buttons are not images. They are unicode characters/symbols.
