### ISSUE TITLE
Visual bug with choosing dates

### ISSUE THREAD

**Issue by Theguyhere0** [dragonwocky/notion-enhancer#54]
**describe the bug**
When selecting a date in the database columns, the blue square that indicates the date selected is solid and doesn't show the number underneath it.

**expected behaviour**
The number underneath the blue selection square should be showing.

**screenshots**
![Screenshot (54)](https://user-images.githubusercontent.com/52550799/91465756-0d312980-e843-11ea-9e64-757b938104f9.png)

**platform**
Windows 10

**Comment by Theguyhere0** [comment]
Side note: It also covers up the red circle indicating what the live date is. Both the circle and the number should appear on top of the blue square.

**Comment by dragonwocky** [comment]
circle doesn't appear even in default notion. number missing is a bug tho.
![image](https://user-images.githubusercontent.com/16874139/91519548-4b5b4580-e936-11ea-81f5-ea2ce2ef4f37.png)

**Comment by Theguyhere0** [comment]
Whoops, looks like I remembered it wrong. Ignore my last comment then.
