### ISSUE TITLE
property layout not working

### ISSUE THREAD

**Issue by Guilherme5342** [dragonwocky/notion-enhancer#57]
I activated the property layout enhancement and it didn't apply. It shows as activated but it does't work on notion

![image](https://user-images.githubusercontent.com/53620734/91472393-c278d700-e86d-11ea-9dc6-daecdd760801.png)

Windows 10, desktop Notion

**Comment by Nek-12** [comment]
Have you tried restarting the app?

**Comment by Guilherme5342** [comment]
> Have you tried restarting the app?

yes, multiple times also tried deactivating and activating again, didn't work

**Comment by dragonwocky** [comment]
thanks for reporting this, was caused due to notion updates. fixed by https://github.com/dragonwocky/notion-enhancer/commit/2eee02cfbdbfc74bc1d4ffda10cbc6f676ab145b

**Comment by hdaasari** [comment]
I am facing this issue again in 0.8.5

**Comment by dragonwocky** [comment]
yup, notion seems to have changed things again -_-

**Comment by hdaasari** [comment]
Great! I thought I did some installation wrong.

Great work with the enhancer, love it.
