### ISSUE TITLE
Text color format applied to blocks no longer affects the text within the block

### ISSUE THREAD

**Issue by Theguyhere0** [dragonwocky/notion-enhancer#58]
**describe the bug**
~~After updating the notion enhancer, the coloring of text in pages that are part of databases (not stand-alone pages) was removed and set to white.~~

Edit: After several comments, it appears that the real bug is that text color applied to a block does not affect text, only bullets and toggle arrows. This issue does not affect highlighting or any color formatting applied to the text itself.

**expected behaviour**
~~Color should not be set to white after the update.~~

Edit: Applying text color to a block should change the color of text within the block.

**screenshots**
This is what it looks like (this is a template, it also affects templates):
![Screenshot (55)](https://user-images.githubusercontent.com/52550799/91476259-964f5d00-e851-11ea-85ec-0396c922066f.png)

This is what it looked like before:
![Screenshot (56)](https://user-images.githubusercontent.com/52550799/91476277-9e0f0180-e851-11ea-92ac-3f8e197c0ddb.png)

More screenshots of the issue in the comments section.

**platform**
Windows 10

**Comment by Theguyhere0** [comment]
**Note:** This seems to only affect headers that are not highlighted. Possibly an issue with formatting the letters themselves without formatting the entire text block.

**Comment by Guilherme5342** [comment]
I saw this post and than I realized mine changed too, but the strange thing is that not all of them changed

![image](https://user-images.githubusercontent.com/53620734/91478866-fb697980-e876-11ea-8a6e-ac8cd0f16e16.png)
the "EngNet" stayed how all of them were

**Comment by TarunTikkoo** [comment]
> **Note:** This seems to only affect headers that are not highlighted. Possibly an issue with formatting the letters themselves without formatting the entire text block.

It certainly seems to be an issue to do with format text vs formatting a block. I have a similar bug with toggles and bullets. Below I have set the entire toggle block to be red in colour however only the toggle icon is red.
![image](https://user-images.githubusercontent.com/10113860/91502015-657f2e80-e90a-11ea-8d0a-0c054b235ca0.png)

If I highlight a bullet point block and change the colour to red, only the bullet becomes red:
![image](https://user-images.githubusercontent.com/10113860/91502124-ac6d2400-e90a-11ea-95f3-0044df524b0d.png)

However, highlight just the text and _not_ the block allows the text to be coloured as it should:
![image](https://user-images.githubusercontent.com/10113860/91502182-ce66a680-e90a-11ea-98f9-5450e231d09a.png)
