### ISSUE TITLE
macos extensions not enabling

### ISSUE THREAD

**Issue by afekateam** [dragonwocky/notion-enhancer#60]
**describe the bug**
RTL is enabled but doesn't have any impact 

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/11197129/91562259-9892e380-e945-11ea-9faa-e7e5c7d77105.png)
![image](https://user-images.githubusercontent.com/11197129/91562341-bb24fc80-e945-11ea-8eb2-69d55c75ae8b.png)

**platform**
macOS

**Comment by dragonwocky** [comment]
you definitely reloaded the app + tried typing some new stuff to trigger it?

**Comment by afekateam** [comment]
Of course. After launching the app the RTL is back to be disabled.

**Comment by dragonwocky** [comment]
as in, disabled in the enhancements menu? does that happen with any other extensions?

**Comment by afekateam** [comment]
Yes, I try to enable some other extensions, and it the same result.
notion-enhancer check
notion-enhancer v0.8.0 applied.

**Comment by dragonwocky** [comment]
can you try opening the console (have the enhancements menu focused, then do `Command+Option+J`) and seeing what it says in there?

**Comment by afekateam** [comment]
I am not sure what I shude to do.

**Comment by dragonwocky** [comment]
1. open notion
2. open the enhancements menu
3. do the keyboard combination/shortcut `Command+Option+J`
4. send me a screenshot of the window that opens

**Comment by afekateam** [comment]
OK the window is not open
I do the keyboard combination when the following window on the screen 
![image](https://user-images.githubusercontent.com/11197129/91564716-b3675700-e949-11ea-9a43-4aca5bbcfccc.png)

**Comment by dragonwocky** [comment]
try `Command+Option+I` or `CTRL+SHIFT+I` instead

**Comment by afekateam** [comment]
![image](https://user-images.githubusercontent.com/11197129/91566369-3be6f700-e94c-11ea-986d-3a928cd9416c.png)

**Comment by dragonwocky** [comment]
ok, now if you go to the tab at the top that says console, what's in there?

**Comment by afekateam** [comment]
![image](https://user-images.githubusercontent.com/11197129/91566786-d810fe00-e94c-11ea-9810-6f087bcb512c.png)

**Comment by dragonwocky** [comment]
hm, alright... i have experienced this before but only once: try fulling shutting down notion (go to the menu at the top and click "quit"), so not even the icon shows, and once it's reopened try again. i don't know what caused it but that fixed it for me.

**Comment by afekateam** [comment]
![image](https://user-images.githubusercontent.com/11197129/91567221-7735f580-e94d-11ea-9d06-b91fb99deb73.png)
After I enable RTL

**Comment by dragonwocky** [comment]
alright thankyou. i'll see what i can do.

**Comment by dragonwocky** [comment]
just checking - you definitely ran the enhancer with the same user account as the one you installed/opened notion with?
is that an admin account?

**Comment by dragonwocky** [comment]
if you run `sudo chmod -R 777 /Users/idantrahman/.notion-enhancer` and then try using the menu, does that work?

**Comment by afekateam** [comment]
Perfect!! I run a command and then reset an app.
Now, evrythig is working well.
Thank you very much!!
