### ISSUE TITLE
v0.8.1 was working but can't install after v0.8.2

### ISSUE THREAD

**Issue by x-Lupin** [dragonwocky/notion-enhancer#62]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
npm comes back with an error after trying to run.

**expected behaviour**
why is this a bug - what should be happening?
Should install successfully.

**screenshots**
if applicable, add screenshots of your problem.
![error](https://user-images.githubusercontent.com/66743131/91583629-684d4400-e949-11ea-9200-73a5d32aaac3.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
Windows 10

**Comment by dragonwocky** [comment]
does v0.8.3 fix this?

**Comment by Crimson723** [comment]
No the 0.8.3 is leaving same error for me.

**Comment by Crimson723** [comment]
Notion app isn't even opening after the error.

**Comment by x-Lupin** [comment]
yes, although I had to delete the files from the npm folder regarding this project (I did this with the v0.8.2 update too and it didn't work)

on the v0.8.1 it updated without this error or the need to delete files

**Comment by dragonwocky** [comment]
yeah, the v0.8.2 update was a bit broken...

@Crimson723 what platform are you on? try doing `npm remove -g notion-enhancer` and then `npm i -g notion-enhancer`.

**Comment by x-Lupin** [comment]
did you delete the files in the npm folder and try again? @Crimson723 
that solved the issue for me, updated fine and the app is up and running (just have to reapply settings after)

**Comment by Crimson723** [comment]
Yeah. clearing the npm folder worked for me too.
