### ISSUE TITLE
css not loading under proxy

### ISSUE THREAD

**Issue by MidNightBlackCat** [dragonwocky/notion-enhancer#66]
why looks like this..2 pictures

![image](https://user-images.githubusercontent.com/14031735/91625559-f58ca900-e9da-11ea-8c0a-affc9def9121.png)
![image](https://user-images.githubusercontent.com/14031735/91625567-00dfd480-e9db-11ea-9d83-86fe2edb8e42.png)

**Comment by dragonwocky** [comment]
what platform are you on?

click/focus on the main notion window, then try `Command+Option+I` or `CTRL+SHIFT+I` - one of them will open a new window. click "console" up the top of that, then send a screenshot of what it shows.

**Comment by MidNightBlackCat** [comment]
> what platform are you on?
> 
> click/focus on the main notion window, then try `Command+Option+I` or `CTRL+SHIFT+I` - one of them will open a new window. click "console" up the top of that, then send a screenshot of what it shows.

I'm using Windows 10, here's the screenshot:
![image](https://user-images.githubusercontent.com/14031735/91625692-0b4e9e00-e9dc-11ea-93c1-5078dc3f075a.png)

**Comment by dragonwocky** [comment]
does v0.8.5 fix this?

**Comment by MidNightBlackCat** [comment]
> does v0.8.5 fix this?

Have the npm repository updated 0.8.5 version? I still got 0.8.4 by using `npm i -g notion-enhancer`

**Comment by dragonwocky** [comment]
it definitely has been... try `npm i -g notion-enhancer@v0.8.5`
![image](https://user-images.githubusercontent.com/16874139/91631424-b54e1a80-ea1c-11ea-8761-5796da4375d6.png)

**Comment by MidNightBlackCat** [comment]
> it definitely has been... try `npm i -g notion-enhancer@0.8.5`
> ![image](https://user-images.githubusercontent.com/16874139/91631424-b54e1a80-ea1c-11ea-8761-5796da4375d6.png)

emmm, seams still not working
![image](https://user-images.githubusercontent.com/14031735/91631583-41584600-ea0d-11ea-82ae-bc1165c82d94.png)
![image](https://user-images.githubusercontent.com/14031735/91631591-4cab7180-ea0d-11ea-8973-fc144ef2ba8a.png)
![image](https://user-images.githubusercontent.com/14031735/91631589-487f5400-ea0d-11ea-87aa-f3b823b61d55.png)

**Comment by dragonwocky** [comment]
not sure what's going on then, and i can't replicate it myself.

**Comment by MidNightBlackCat** [comment]
> not sure what's going on then, and i can't replicate it myself.
> 
> you're definitely an admin user + did the enhancer installation from the same user acct as you're running the notion app?

yes sure, the elder version works normally.. BTW I'm behand the company VPN, let me try on my own laptop later...

**Comment by dragonwocky** [comment]
i'm on the same platform- and yeah, you should be able to use it fine behind a proxy, but self-signed certificates can break the installation.

by older version do you mean v0.8.0 or v0.7.0 (python)?

**Comment by MidNightBlackCat** [comment]
> i'm on the same platform- and yeah, you should be able to use it fine behind a proxy, but self-signed certificates can break things during the installation.
> 
> by older version do you mean v0.8.0 or v0.7.0 (python)?

I tried on my laptop, works normally. Same platform same version.
Maybe because of the proxy, is there any other ways to install new version?


the older version means python version(which may be v0.7.0)

**Comment by dragonwocky** [comment]
@MidNightBlackCat you can manually [download the repo](https://github.com/dragonwocky/notion-enhancer/archive/v0.8.5.zip), go into it in your cmd prompt and run `npm link`.

**Comment by MidNightBlackCat** [comment]
> into it in your cmd p

Seems still not working.
But it's ok, I will check by myself. Or I will not use on company PC...😭

**Comment by dragonwocky** [comment]
@MidNightBlackCat try doing exactly this:
1. download the repo.
2. unzip the download.
3. open the command prompt.
4. remove the previous install of the enhancer: `npm remove -g notion-enhancer`
3. go to the folder you downloaded (e.g. `cd C:\Users\MidNightBlackCat\Documents\notion-enhancer`).
5. link that folder as the enhancer: `npm link`
6. apply the enhancer: `notion-enhancer apply -y`

**Comment by MidNightBlackCat** [comment]
> @MidNightBlackCat try doing exactly this:
> 
> 1. download the repo.
> 2. unzip the download.
> 3. open the command prompt.
> 4. remove the previous install of the enhancer: `npm remove -g notion-enhancer`
> 5. go to the folder you downloaded (e.g. `cd C:\Users\MidNightBlackCat\Documents\notion-enhancer`).
> 6. link that folder as the enhancer: `npm link`
> 7. apply the enhancer: `notion-enhancer apply -y`
> 
> sorry, my instructions before were pretty unclear, so you probably didn't remove the old install of the enhancer.

Thank you for your kindly reply. I just do as the new instruction, but still shows the same error. Maybe not the installation issue.
It's ok, it works normally not behind a proxy 😢 ...
