### ISSUE TITLE
Blue tags are purple.

### ISSUE THREAD

**Issue by ourhalcyondays** [dragonwocky/notion-enhancer#67]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?
**>Blue tags are purple instead of blue across entire app.**

**expected behaviour**
why is this a bug - what should be happening?
**>Blue tags should be blue, not purple.**

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/70455008/91647781-aff8cc00-ea2c-11ea-809d-f54da12336b5.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
**>Windows 10**

**Comment by mburstiner** [comment]
Having this problem too across all themes!

**Comment by dragonwocky** [comment]
known issue, just a typo I missed in the last release. will be fixed in the next update.
