### ISSUE TITLE
collapse properties in page view

### ISSUE THREAD

**Issue by eliteplow** [dragonwocky/notion-enhancer#68]
**problem**
Some Databases have many properties, and it blocks the page.

**solution**
 It would be very helpful to have the option to be able to choose what properties are shown, and what is behind a Toggle List Selector. Or in a more simple manner - an option to hide and collapse all the properties by choice.

Thank you!

**Comment by dragonwocky** [comment]
@eliteplow this is already a feature - try the `property layout` extension.
