### ISSUE TITLE
notion-enhancer shortcut key `ctrl + e` conflicts with notion's mark as code

### ISSUE THREAD

**Issue by spencerwooo** [dragonwocky/notion-enhancer#70]
**describe the bug**

Nothing too serious, just a simple keybinding conflict. Every time I use the shortcut <kbd>ctrl + e</kbd> to convert inline code, the notion enhancer also pops up.

**expected behaviour**

- Notion enhancer won't popup on <kbd>ctrl + e</kbd> if I selected something inside notion (which indicates that i'm going to format the text instead of bringing up notion enhancer), or...
- Make an option to set the shortcut key for bringing up notion enhancer?

**screenshots**

![image](https://user-images.githubusercontent.com/32114380/91718356-c5edc480-ebc5-11ea-8086-f0370671fd71.png)

**platform**

Windows 10

**Comment by dragonwocky** [comment]
hm, hadn't noticed that, thanks
