### ISSUE TITLE
Config reset

### ISSUE THREAD

**Issue by Guilherme5342** [dragonwocky/notion-enhancer#71]
Every time I update the version of the enhancer all my enchancer configs are reseted, theme, dark+ color, tray options(I like to desactivate the close to the tray) and enhancements selected

Windows 10, desktop app

**Comment by dragonwocky** [comment]
how do you update?

**Comment by Guilherme5342** [comment]
using npm i -g notion-enhancer on the cmd

**Comment by dragonwocky** [comment]
do you remove the previous version?

**Comment by Guilherme5342** [comment]
no

**Comment by Guilherme5342** [comment]
I and I don't unapply it

**Comment by dragonwocky** [comment]
alright found the bug, will be fixed in the next release (though since it's still in the current version it will still happen that once).

**Comment by theotheo** [comment]
I've met the same issue. I am on Ubuntu and not sure that it related to app's update. It seems the settings just reset periodically.
It's a bit annoying. Any advice would be appreciated!

**Comment by dragonwocky** [comment]
@theotheo though the "symptoms" appear similar, the cause and situation in which the settings reset occur are different. Please open a new bug report in https://github.com/notion-enhancer/repo for this - my guess is that it's related to having too many tabs open at once.
