### ISSUE TITLE
Blue color replaced

### ISSUE THREAD

**Issue by Guilherme5342** [dragonwocky/notion-enhancer#72]
The blue color was replaced by purple

![image](https://user-images.githubusercontent.com/53620734/91734462-57871300-eb81-11ea-9625-00a495c0d727.png)

I'm using the dark+ theme
windows 10, desktop app

**Comment by AeriaHane** [comment]
This was already noted [here](https://github.com/dragonwocky/notion-enhancer/issues/67#issue-688619513)

**Comment by Guilherme5342** [comment]
oh, sorry, didn't saw that one
