### ISSUE TITLE
scrolling to today in calender view

### ISSUE THREAD

**Issue by r-alfassi** [dragonwocky/notion-enhancer#74]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**problem**
must scroll down to see the current date unless its early in the month

**solution**
is it possible to make the first raw of days - the current week?

**alternatives (optional)**
have you tried to do this yourself? have you seen it done somewhere else?
would a different feature remove the need for this?

**Comment by dragonwocky** [comment]
it's possible to automatically scroll down, but that means if you wanted to see the filter/sort/new buttons you have to scroll back up, which can be just as annoying.

what i will do is add a button to scroll down for you (assuming today is loaded on the calendar).
![image](https://user-images.githubusercontent.com/16874139/91824709-89ca6a80-ec7e-11ea-8909-7323db604924.png)
