### ISSUE TITLE
app.asar not found

### ISSUE THREAD

**Issue by shreya-shah** [dragonwocky/notion-enhancer#79]
**platform**
ubuntu

**installation steps**
I installed using the [deb builder](https://github.com/davidbailey00/notion-deb-builder/) 

- i can't find the app.asar

I don't know exactly how to apply the themes using the enhancer.
I have run the command `notion-enhancer apply`, the output for which is:
```
 ...unpacking app.asar
### ERROR ###
Error: ENOENT: no such file or directory, open '/usr/lib/notion-desktop/resources/app.asar'

```

**Comment by dragonwocky** [comment]
the deb builder no longer works as it doesn't generate an app.asar file - it'll be removed from the list of supported platforms next time I update the repo. try using the [notion-app](https://github.com/jaredallard/notion-app) installer instead.
