### ISSUE TITLE
Auto open as a page and set to full width

### ISSUE THREAD

**Issue by Mara-Li** [dragonwocky/notion-enhancer#81]
**problem**
I must always open as a page + set to full width, i lost some times to do that, and would prefere a trick in the enhancer to automatically do that. 

**solution**
The feature can be implemented as in the other enhancement, and maybe can be separate between the two, for people who want just one or the two.

**Comment by dragonwocky** [comment]
the bypassing having to click "open as page" i've made a module for, it will be released with the next update soon.
however, setting a page to full width involves changing actual page data, which the enhancer can't do at the moment.

**Comment by dragonwocky** [comment]
though actually toggling the full width option is still out of scope, a page will be able to visually appear full width via setting `--theme_dark--page_normal-width`/`--theme_light--page_normal-width` to 100% in the next release. this is default behaviour if you have the "neutral" theme enabled.
