### ISSUE TITLE
All themes have bugged "Blue" colour?

### ISSUE THREAD

**Issue by Ragonfana** [dragonwocky/notion-enhancer#83]
Using Windows 10. Unless this is intended - each theme seems to have the "Blue" colour on the Select property type to be the same colour purple as the actual "Purple" colour. This doesn't apply to text colours or text highlights. Screenshots below of the colour menus for each theme (labelled):
Dark+:
![image](https://user-images.githubusercontent.com/13308218/92288875-8cc29680-eedc-11ea-93e1-79cce5a6695c.png)
Gameish:
![image](https://user-images.githubusercontent.com/13308218/92288889-96e49500-eedc-11ea-951d-af8a23ee828e.png)
Neutral:
![image](https://user-images.githubusercontent.com/13308218/92288901-9fd56680-eedc-11ea-8ef9-54d58c02c3e8.png)
Pastel Dark:
![image](https://user-images.githubusercontent.com/13308218/92288905-a8c63800-eedc-11ea-8633-5e167742e770.png)

**Comment by dragonwocky** [comment]
known bug, a fix will come out with the next release

**Comment by fabiosangregorio** [comment]
@dragonwocky I was about to open a new issue for this. Can I suggest reopening this as this is not fixed yet? Maybe adding a "awaiting-release" tag would be clearer.

**Comment by dragonwocky** [comment]
that's probably a better way of doing it, yeah - was just trying to make it clear to myself what i needed to do and what i didn't.
