### ISSUE TITLE
The easy option of Custom Fonts 

### ISSUE THREAD

**Issue by pranjalyadav451** [dragonwocky/notion-enhancer#85]
The older version of notion enhancer was not as polished but in some aspects it allowed for more controls and the option of having your own fonts was a game - changer for me.
I would be pf great help if you add the option back to do that or if the option is still present (which I cannot find ) if you could add it to the documentation how to change the default fonts step by step in the Documentation.
It would be of great help.
By the way you are helping so many people you don't know with this piece of software.
**Thank You for that**

**Comment by dragonwocky** [comment]
You can still do custom fonts via the custom inserts module that lets you add your own CSS (equivalent to the old `user.css`). The [tweaks page](https://github.com/dragonwocky/notion-enhancer/blob/master/TWEAKS.md) describes how to do it.

The code specifically to do fonts has changed to be more compatible with themes, that's all. E.g. to change the main/sans-serif font in the dark theme you would do:
```css
:root {
  --theme_dark--font_sans: 'font name here';
}
```
A full list of variables is available [here](https://github.com/dragonwocky/notion-enhancer/blob/master/mods/core/css/variables.css) - if you read through the update guide / the tweaks page / the developer documentation properly then all of this is explained and linked to. Simple? Perhaps not at first, though once you've got your head wrapped around it it is. Powerful? Definitely.

(In the next update an extension is coming out that lets you change fonts from the GUI, anyway.)
