### ISSUE TITLE
Estimated reading times

### ISSUE THREAD

**Issue by mike-lowski** [dragonwocky/notion-enhancer#88]
**Problem**
I've seen in the app Ulysses you can see 3 estimated reading times for slow reading, normal reading and fast reading. I think this feature would be cool to implement based on the total words of any notion page.

**Solution**
Ranges could be something like this:

Slow (150 wpm)
Normal (200 wpm)
Fast (250 wpm)

**Comment by dragonwocky** [comment]
That's a pretty cool idea - I'll see what I can do.

**Comment by dragonwocky** [comment]
Would it be more helpful to have the three speeds, or to have it more like on wordcounter.net with a wordcount + avg. speaking time + avg. reading time?

**Comment by mike-lowski** [comment]
I think that's even better considering speaking time is kinda like slow reading time.

**Comment by dragonwocky** [comment]
needs work, but the info is there:
![image](https://user-images.githubusercontent.com/16874139/93475466-f9f21500-f93b-11ea-893b-087a80641c56.png)
