### ISSUE TITLE
change/remove the "Ctrl + E" hotkey to open notion-enhancer options

### ISSUE THREAD

**Issue by Hmmmmmmmmmm** [dragonwocky/notion-enhancer#90]
**problem**
When i try using Notion to write code, the  "Ctrl + E" hotkey conflicts with **Notion hotkey** of "inline code", which is frustrating and almost unable to use.

**solution**
Add a switch of this hotkey or change/remove the hotkey to open notion-enhancer options.

**Comment by dragonwocky** [comment]
duplicate of #70, fix already done and will be released soonish
