### ISSUE TITLE
The integrated scrollbars don't run well

### ISSUE THREAD

**Issue by Septem-YDL** [dragonwocky/notion-enhancer#94]
FILL OUT THIS TEMPLATE, REMOVING/REPLACING EVERYTHING HERE WITH YOUR OWN INFORMATION.
BE AS CLEAR AND CONCISE AS POSSIBLE.

**describe the bug**
what is the bug - what happens?

**expected behaviour**
The integrated Scrollbars didn't work, after reload the window or relaunch.
particularly the scrollbar of the sidebar.

**screenshots**
if applicable, add screenshots of your problem.
![image](https://user-images.githubusercontent.com/71010871/92586959-91ff5700-f2c9-11ea-9da4-c7d76d52e2dd.png)

**platform**
what OS are you using? e.g. windows 7, windows 10, WSL, ubuntu, arch linux, macOS
Windows 10, 2004

**Comment by Septem-YDL** [comment]
After a few tests, i find out how to trigger this error
it will happen when you change the zoom of the window and reload the page.
When you reset the zoom as 100% and reload the window again, it will work well again.
but as you know, the default size of notion isn't big enough for me, so i will zoom it as 110% usually.

**Comment by dragonwocky** [comment]
Yeah, this has been happening to me too... thought I'd fixed it for a while, then it came back.
Usually just reloading once or twice makes it go away no matter the zoom.
A permanent solution would be nice but I'm yet to figure one out.

**Comment by Septem-YDL** [comment]
Thank you for your reply.
Just let it be until the solution come out.
Thanks for your works.
