### ISSUE TITLE
Color Selection Issue

### ISSUE THREAD

**Issue by shunnkou** [dragonwocky/notion-enhancer#99]
The bug is the tag colors.

"Blue" shows up as purple instead of blue.

![image](https://user-images.githubusercontent.com/50721364/92997810-0dd4eb80-f4e4-11ea-83b5-7198e1e588b8.png)

I'm using Windows 10.

**Comment by dragonwocky** [comment]
dup of https://github.com/dragonwocky/notion-enhancer/issues/83
